mgr_dummies = 134
with open('./tmp_out.cpp','w') as f:
    f.write('// Auto-scaffolded catalog TU for kyoshin/cf/CCharEffectEne\n')
    f.write('// High-level C++ reconstruction from retail ASM.\n\n')
    f.write('#include <types.h>\n')
    f.write('#include "kyoshin/cf/CCharEffect.hpp"\n')
    f.write('#include "kyoshin/cf/object/CfObjectMove.hpp"\n')
    f.write('#include "kyoshin/cfsys/CfObjectImplPc.hpp"\n')
    f.write('#include "kyoshin/cf/object/CfObjectEff.hpp"\n\n')
    f.write('// External data tables\n')
    f.write('extern "C" u16 lbl_eu_80501E48[];\n')
    f.write('extern "C" u16 lbl_eu_80501EB8[];\n')
    f.write('extern "C" u16 lbl_eu_80501F28[];\n')
    f.write('extern "C" u16 lbl_eu_80501F98[];\n')
    f.write('extern "C" void* func_8008187C__Q22cf13CfGameManagerFv(u32 value);\n')
    f.write('extern "C" void* func_800817BC__Q22cf13CfGameManagerFv(u32 value, u32 unused);\n')
    f.write('extern "C" void func_800ACF78(void* obj, void* mgr, u32 val);\n')
    f.write('extern "C" void func_800ACEF8(void* obj, const void* src);\n')
    f.write('extern "C" void func_800ACC50(void* self);\n')
    f.write('extern "C" void func_80484EB0(void* ptr);\n')
    f.write('extern "C" u8 lbl_eu_8052FDD8[];\n')
    f.write('extern "C" void* __ct__CCharEffect(void* self);\n\n')
    f.write('// CCharEffectEne layout (inherits CCharEffect, vptr at 0)\n')
    f.write('struct CCharEffectEne {\n')
    f.write('    u8 pad_000[0x26C];\n')
    f.write('    u16 mFlags;\n')
    f.write('    u8 pad_26E[0x2E];\n')
    f.write('    void* mManager;\n')
    f.write('};\n\n')
    f.write('// Manager interface at vtable offset 0x220 (retail CfObjectMove slot)\n')
    f.write('struct MgrIf {\n')
    for i in range(mgr_dummies):
        f.write(f'    virtual void d{i:03d}();\n')
    f.write('    virtual void* get220(u32 id);\n')
    f.write('};\n\n')
    f.write('extern "C" CCharEffectEne* __ct__cf_CCharEffectEne(CCharEffectEne* self) {\n')
    f.write('    __ct__CCharEffect(self);\n')
    f.write('    *(void**)self = lbl_eu_8052FDD8;\n')
    f.write('    self->mFlags |= 1;\n')
    f.write('    return self;\n')
    f.write('}\n\n')
    f.write('extern "C" void* func_8015CD04(CCharEffectEne* self, u32 index, s32 mode) {\n')
    f.write('    void* result = nullptr;\n')
    f.write('    if (mode < 0) {\n')
    f.write('        u16 entry = lbl_eu_80501E48[index];\n')
    f.write('        if (entry != 0) {\n')
    f.write('            if (entry < 0x200) {\n')
    f.write('                result = func_8008187C__Q22cf13CfGameManagerFv(entry);\n')
    f.write('            } else {\n')
    f.write('                result = reinterpret_cast<MgrIf*>(self->mManager)->get220(entry - 0x200);\n')
    f.write('            }\n')
    f.write('        }\n')
    f.write('    } else {\n')
    f.write('        result = reinterpret_cast<MgrIf*>(self->mManager)->get220((u32)mode);\n')
    f.write('    }\n')
    f.write('    return result;\n')
    f.write('}\n\n')
    f.write('extern "C" void* func_8015CD9C(CCharEffectEne* self, u32 index, s32 mode) {\n')
    f.write('    void* obj = nullptr;\n')
    f.write('    if (mode < 0) {\n')
    f.write('        u16 entry = lbl_eu_80501EB8[index];\n')
    f.write('        if (entry != 0) {\n')
    f.write('            obj = reinterpret_cast<MgrIf*>(self->mManager)->get220(entry);\n')
    f.write('        }\n')
    f.write('    } else {\n')
    f.write('        obj = reinterpret_cast<MgrIf*>(self->mManager)->get220((u32)mode);\n')
    f.write('    }\n')
    f.write('    if (obj != nullptr) {\n')
    f.write('        func_800ACF78(obj, self->mManager, 0);\n')
    f.write('    }\n')
    f.write('    return obj;\n')
    f.write('}\n\n')
    f.write('extern "C" void* func_8015CE44(CCharEffectEne* self, u32 index, s32 mode) {\n')
    f.write('    void* obj = nullptr;\n')
    f.write('    if (mode < 0) {\n')
    f.write('        u16 entry = lbl_eu_80501F28[index];\n')
    f.write('        if (entry != 0) {\n')
    f.write('            obj = func_8008187C__Q22cf13CfGameManagerFv(entry);\n')
    f.write('        }\n')
    f.write('    } else {\n')
    f.write('        obj = func_800817BC__Q22cf13CfGameManagerFv((u32)mode, 0);\n')
    f.write('    }\n')
    f.write('    if (obj != nullptr) {\n')
    f.write('        func_800ACF78(obj, self->mManager, 0);\n')
    f.write('    }\n')
    f.write('    return obj;\n')
    f.write('}\n\n')
    f.write('extern "C" void* func_8015CED0(CCharEffectEne* self, u32 index, s32 mode) {\n')
    f.write('    void* obj = nullptr;\n')
    f.write('    if (mode < 0) {\n')
    f.write('        u16 entry = lbl_eu_80501F98[index];\n')
    f.write('        if (entry != 0) {\n')
    f.write('            if (entry < 0x200) {\n')
    f.write('                obj = func_8008187C__Q22cf13CfGameManagerFv(entry);\n')
    f.write('                if (obj != nullptr) {\n')
    f.write('                    func_800ACF78(obj, self->mManager, 0);\n')
    f.write('                }\n')
    f.write('            } else {\n')
    f.write('                obj = reinterpret_cast<MgrIf*>(self->mManager)->get220(entry - 0x200);\n')
    f.write('            }\n')
    f.write('        }\n')
    f.write('    } else {\n')
    f.write('        obj = reinterpret_cast<MgrIf*>(self->mManager)->get220((u32)mode);\n')
    f.write('    }\n')
    f.write('    return obj;\n')
    f.write('}\n\n')
    f.write('extern "C" void func_8015CF90(CCharEffectEne* self, void* target, u32 type, u32 flags) {\n')
    f.write('    void* mgr;\n')
    f.write('    void* data;\n')
    f.write('    void* dataSrc;\n')
    f.write('    u32 bitFlag, subtype;\n')
    f.write('    mgr = self->mManager;\n')
    f.write('    dataSrc = *(void**)((u8*)mgr + 0x98);\n')
    f.write('    if (dataSrc == nullptr) return;\n')
    f.write('    bitFlag = (flags >> 7) & 1;\n')
    f.write('    subtype = flags & 0x7F;\n')
    f.write('    dataSrc = nullptr;\n')
    f.write('    if (mgr != nullptr) {\n')
    f.write('        mgr = (void*)((u8*)mgr - 0x3E9C);\n')
    f.write('    }\n')
    f.write('    data = nullptr;\n')
    f.write('    if (type == 0xA || type == 0xC || type == 0xE || type == 0x19 || subtype == 2) {\n')
    f.write('        data = *(void**)((u8*)mgr + 0x4594);\n')
    f.write('    } else if (type == 0xB || type == 0xD || type == 0xF || subtype == 3) {\n')
    f.write('        data = *(void**)((u8*)mgr + 0x4598);\n')
    f.write('    }\n')
    f.write('    if (data != nullptr) {\n')
    f.write('        dataSrc = reinterpret_cast<void*>(reinterpret_cast<CfObjectImplPcTgt*>(data)->vfA8());\n')
    f.write('    }\n')
    f.write('    func_800ACF78(target, self->mManager, (u32)(uintptr_t)dataSrc);\n')
    f.write('    reinterpret_cast<cf::CfObjectEff*>(target)->func_800ACF50(bitFlag != 0);\n')
    f.write('    func_800ACEF8(target, (void*)((u8*)(*(void**)((u8*)self->mManager + 0x98)) + 0x304));\n')
    f.write('    func_80484EB0(*(void**)((u8*)self->mManager + 0x98));\n')
    f.write('    func_800ACC50(target);\n')
    f.write('}\n')
