#!/usr/bin/env python3
"""Committed code-smell report + CI gate for the game-code translation units.

Scans the game-code C++ TUs (src/kyoshin, libs/monolib/src, libs/nw4r/src)
for the smell families tracked by the team and writes a deterministic report
to docs/CODE_SMELLS.md.

Usage:
    python3 tools/coop/smell_report.py --write          # regenerate docs/CODE_SMELLS.md
    python3 tools/coop/smell_report.py --check          # CI gate: stale OR per-TU regression -> exit 1
    python3 tools/coop/smell_report.py --check --no-strict  # freshness only (no regression gate)
    python3 tools/coop/smell_report.py --completeness   # live TU status from targets.json (stdout only)

--check (CI):
  1. freshness: the committed docs/CODE_SMELLS.md must equal what --write
     produces for the current tree. Any src change that alters a smell count
     forces a regeneration (visible in the PR diff, like readme_status.py).
  2. regression (strict): per-TU smell metrics must not *increase* relative
     to the baseline committed on the base branch (origin/main by default,
     or --base <ref>, or HEAD~1 as a local fallback). TUs absent from the
     base baseline (new files) are exempt; cleanup that reduces counts is
     always allowed. This cannot be defeated by regenerating the report in
     the same PR, because the comparison source is the base branch's copy.

--completeness: prints the TU status table derived from the target registry
(tools/coop/targets.json) — the replacement for the retired ALL_TUS.md.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.coop.smell_scan import Stats, scan_file  # noqa: E402

REPORT = ROOT / "docs" / "CODE_SMELLS.md"
BEGIN_BASELINE = "<!-- BEGIN BASELINE -->"
END_BASELINE = "<!-- END BASELINE -->"

# Game-code C++ roots scanned for smells (SDK C code is out of scope).
ROOTS = ("src/kyoshin", "libs/monolib/src", "libs/nw4r/src")

# metric key (Stats attr) -> display name
METRICS = (
    ("extern_c_nonlbl_decl", "extC-decl"),
    ("extern_c_nonlbl_def", "extC-def"),
    ("self_params", "self"),
    ("void_ptr", "void*"),
    ("ptr_arith", "ptr-arith"),
    ("deref_arith", "deref-arith"),
    ("asm_code", "asm"),
    ("rn_params", "rN"),
    ("goto_count", "goto"),
)
SEVERITY_WEIGHTS = {  # cleanable-smell weight for the top-offenders list
    "extern_c_nonlbl_decl": 1,
    "extern_c_nonlbl_def": 2,
    "self_params": 2,
    "self_access": 1,
    "void_ptr": 1,
    "void_ptr_cast": 1,
    "ptr_arith": 1,
    "deref_arith": 1,
    "asm_code": 3,
    "rn_params": 2,
}


def scan_all() -> dict[str, Stats]:
    rows: dict[str, Stats] = {}
    for root in ROOTS:
        for f in sorted((ROOT / root).rglob("*.cpp")):
            rel = Path(f).relative_to(ROOT)
            rows[str(rel)] = scan_file(f)
    return rows


def severity(s: Stats) -> int:
    return sum(getattr(s, k) * w for k, w in SEVERITY_WEIGHTS.items())


def totals(rows: dict[str, Stats]) -> Stats:
    t = Stats()
    for s in rows.values():
        for k, _ in METRICS:
            setattr(t, k, getattr(t, k) + getattr(s, k))
        t.extern_c_total += s.extern_c_total
        t.extern_c_lbl += s.extern_c_lbl
        t.self_access += s.self_access
        t.void_ptr_cast += s.void_ptr_cast
        t.pragma += s.pragma
    return t


def baseline_json(rows: dict[str, Stats]) -> str:
    bl = {}
    for path, s in sorted(rows.items()):
        metrics = {k: getattr(s, k) for k, _ in METRICS if getattr(s, k) > 0}
        if metrics:
            bl[path] = metrics
    return json.dumps(bl, sort_keys=True, indent=1)


def render_report(rows: dict[str, Stats]) -> str:
    tot = totals(rows)
    lines: list[str] = []
    lines.append("# Code Smell Report")
    lines.append("")
    lines.append("<!-- GENERATED by tools/coop/smell_report.py --write. Do not edit by hand. -->")
    lines.append("")
    lines.append(
        "Tracks the legacy hand-written TU smell families (extern \"C\" outside `lbl_*`, "
        "`self` free-function params, `void*`, raw pointer arithmetic, register-named "
        "params, inline asm, goto chains). New harness-produced code is already gated by "
        "`tools/llm_decomp/lint.py`; this report makes the legacy backlog visible and "
        "prevents it from growing. **Goal: every number in this table trends to 0.**"
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Files scanned: {len(rows)} C++ TUs across {', '.join('`' + r + '`' for r in ROOTS)}")
    lines.append("")
    lines.append("| metric | count |")
    lines.append("|---|---|")
    total_row = {
        "extern_c_total": "extern \"C\" (total lines)",
        "extern_c_nonlbl_decl": "extern \"C\" declarations (non-lbl_*, imports)",
        "extern_c_nonlbl_def": "extern \"C\" definitions (forced names)",
        "self_params": "`self`/register-style params",
        "void_ptr": "`void*` (params + locals)",
        "ptr_arith": "raw pointer offset arithmetic",
        "deref_arith": "deref-through-cast arithmetic",
        "asm_code": "inline asm / `register`",
        "rn_params": "rN-named params",
        "goto_count": "goto",
        "pragma": "#pragma",
    }
    for k, label in total_row.items():
        lines.append(f"| {label} | {getattr(tot, k)} |")
    lines.append("")
    top = sorted(rows.items(), key=lambda kv: -severity(kv[1]))[:10]
    lines.append("## Top offenders (by cleanable severity)")
    lines.append("")
    lines.append("| TU | severity |")
    lines.append("|---|---|")
    for path, s in top:
        lines.append(f"| {path} | {severity(s)} |")
    lines.append("")
    lines.append("## Per-TU metrics")
    lines.append("")
    lines.append("| TU | " + " | ".join(disp for _, disp in METRICS) + " |")
    lines.append("|" + "---|" * (len(METRICS) + 1))
    for path in sorted(rows):
        s = rows[path]
        vals = [str(getattr(s, k)) for k, _ in METRICS]
        if all(v == "0" for v in vals):
            continue
        lines.append(f"| {path} | " + " | ".join(vals) + " |")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- **extern \"C\" is not uniformly a smell.** ~80% of extern \"C\" names are "
        "retail-reloc-mandated (`func_8004B0B0`, `__ct__cf_CfCamFollow`, `lbl_eu_*`, "
        "`func_eu_*`): the retail objects reference those exact names, so the source must "
        "reproduce them. The cleanable subset is the decomp-invented names that appear in "
        "no retail object (`cfCam_*`, `fn`, `getInstance`, ...) — those can become "
        "`static`/member/anonymous-namespace helpers freely."
    )
    lines.append(
        "- **`self` is legit when it is the ABI** (plugin callbacks: `VMThread* self`). "
        "It is a smell when a class already exists in a header and the function could be "
        "a member instead of an `extern \"C\" void* self` free function."
    )
    lines.append(
        "- `void*`→typed-pointer and pointer-arithmetic→struct-field refactors are "
        "**byte-identical** (types are erased at codegen) and the first cleanup to do; "
        "verify with `hexdiff` per function."
    )
    lines.append(
        "- Converting retail-mandated extern \"C\" functions into real C++ members "
        "changes the emitted symbol name and requires a `symbols rename-plan` + "
        "`symbols rename-all` + re-verification ceremony per TU."
    )
    lines.append("")
    lines.append(BEGIN_BASELINE)
    lines.append(baseline_json(rows))
    lines.append(END_BASELINE)
    lines.append("")
    return "\n".join(lines)


def extract_baseline(text: str) -> dict:
    if BEGIN_BASELINE not in text or END_BASELINE not in text:
        return {}
    blob = text.split(BEGIN_BASELINE, 1)[1].split(END_BASELINE, 1)[0].strip()
    try:
        return json.loads(blob)
    except json.JSONDecodeError:
        return {}


def base_report_ref(args) -> str | None:
    for cand in (args.base,) if args.base else ("origin/main", "origin/master", "HEAD~1"):
        if not cand:
            continue
        try:
            out = subprocess.run(
                ["git", "show", f"{cand}:docs/CODE_SMELLS.md"],
                capture_output=True, text=True, cwd=ROOT,
            )
            if out.returncode == 0:
                return out.stdout
        except OSError:
            return None
    return None


def cmd_write(rows: dict[str, Stats]) -> int:
    REPORT.write_text(render_report(rows))
    print(f"wrote {REPORT.relative_to(ROOT)}")
    return 0


def cmd_check(args, rows: dict[str, Stats]) -> int:
    problems: list[str] = []

    # 1. freshness
    if REPORT.exists():
        committed = REPORT.read_text()
        current = render_report(rows)
        if committed != current:
            problems.append(
                f"docs/CODE_SMELLS.md is stale — run "
                f"`python3 tools/coop/smell_report.py --write` and commit the update"
            )
    else:
        problems.append(
            f"docs/CODE_SMELLS.md is missing — run "
            f"`python3 tools/coop/smell_report.py --write` and commit it"
        )

    # 2. strict regression vs base-branch baseline
    if not args.no_strict:
        base_text = base_report_ref(args)
        if base_text:
            base = extract_baseline(base_text)
            if base:
                regressions: list[str] = []
                for path, metrics in sorted(base.items()):
                    cur = rows.get(path)
                    if cur is None:
                        continue  # TU removed
                    for k, disp in METRICS:
                        before = int(metrics.get(k, 0))
                        after = getattr(cur, k)
                        if after > before:
                            regressions.append(f"{path}: {disp} {before} → {after}")
                if regressions:
                    problems.append(
                        "smell regression vs base branch baseline "
                        "(cleanup or consciously re-baseline; new TUs are exempt):\n  "
                        + "\n  ".join(regressions[:20])
                        + (f"\n  … and {len(regressions) - 20} more" if len(regressions) > 20 else "")
                    )

    for p in problems:
        print(f"ERROR: {p}", file=sys.stderr)
    if problems:
        print("\n--check failed.", file=sys.stderr)
        return 1
    print("ok: docs/CODE_SMELLS.md is fresh and no per-TU smell regression vs base.")
    return 0


def cmd_completeness() -> int:
    import collections

    tpath = ROOT / "tools" / "coop" / "targets.json"
    data = json.loads(tpath.read_text())
    targets = data["targets"]
    per_unit: dict[str, list[str]] = collections.defaultdict(list)
    for t in targets:
        per_unit[t["unit"]].append(t["status"])
    rows = []
    for unit, statuses in sorted(per_unit.items()):
        n = len(statuses)
        acc = sum(1 for s in statuses if s in ("FULL_MATCH", "EQUIVALENT_MATCH"))
        if acc == n:
            state = "COMPLETE"
        elif acc > 0:
            state = f"PARTIAL ({acc}/{n})"
        else:
            state = "NO SOURCE" if not (ROOT / "src" / (unit + ".cpp")).exists() else "NOT_STARTED"
        rows.append((unit, n, acc, state))
    print(f"# TU status (live, from tools/coop/targets.json) — {len(rows)} units\n")
    print("| TU | targets | accepted | status |")
    print("|---|---|---|---|")
    for unit, n, acc, state in rows:
        print(f"| {unit} | {n} | {acc} | {state} |")
    print("\nComplete TUs: " + str(sum(1 for r in rows if r[3] == "COMPLETE")))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="regenerate docs/CODE_SMELLS.md")
    ap.add_argument("--check", action="store_true", help="CI gate (freshness + regression)")
    ap.add_argument("--no-strict", action="store_true", help="with --check: freshness only")
    ap.add_argument("--base", default=None, help="base ref for the regression comparison")
    ap.add_argument("--completeness", action="store_true", help="print TU status table (stdout)")
    args = ap.parse_args()

    if args.completeness:
        return cmd_completeness()
    if args.write and args.check:
        ap.error("--write and --check are mutually exclusive")

    rows = scan_all()
    if args.write:
        return cmd_write(rows)
    if args.check:
        return cmd_check(args, rows)
    ap.error("need one of --write, --check, --completeness")


if __name__ == "__main__":
    sys.exit(main())
