#!/usr/bin/env python3
"""Generate Dolphin fixture tables/payloads from the shared Broadway corpus."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.ppc_equivalence.fixtures.corpus import FIXTURES, SANDBOX_BASE, export_jsonl
from tools.ppc_equivalence.fixtures.encode import parse_int

DEFAULT_HEADER = ROOT / "tools" / "test" / "compare_behaviour" / "ppc" / "ppc_fixture_cases.inc"
DEFAULT_PAYLOADS = ROOT / "tools" / "test" / "compare_behaviour" / "ppc" / "ppc_fixture_payloads.c"
DEFAULT_JSONL = ROOT / "tools" / "ppc_equivalence" / "fixtures" / "broadway.jsonl"
CODE_MAX = 16
MEM_WORDS = 32
NAME_MAX = 31


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _gpr_array(initial: dict) -> list[int]:
    regs = [0] * 32
    gpr = initial.get("gpr", {})
    assert isinstance(gpr, dict)
    for name, value in gpr.items():
        if not str(name).startswith("r"):
            continue
        index = int(str(name)[1:])
        regs[index] = parse_int(value) & 0xFFFFFFFF
    return regs


def _fpr_array(initial: dict) -> list[int]:
    regs = [0] * 32
    fpr = initial.get("fpr", {})
    assert isinstance(fpr, dict)
    for name, value in fpr.items():
        if str(name).startswith("f"):
            regs[int(str(name)[1:])] = parse_int(value) & 0xFFFFFFFFFFFFFFFF
    return regs


def _mem_words(initial: dict) -> list[int]:
    words = [0] * MEM_WORDS
    memory = initial.get("memory")
    if not isinstance(memory, dict):
        return words
    bytes_map = memory.get("bytes", memory)
    assert isinstance(bytes_map, dict)
    for key, value in bytes_map.items():
        address = parse_int(key)
        offset = address - SANDBOX_BASE
        if offset < 0 or offset >= MEM_WORDS * 4:
            continue
        word_index = offset // 4
        byte_index = offset % 4
        shift = 24 - 8 * byte_index
        words[word_index] = (words[word_index] & ~(0xFF << shift)) | ((parse_int(value) & 0xFF) << shift)
    return words


def _xer_word(initial: dict) -> int:
    xer = initial.get("xer", {})
    assert isinstance(xer, dict)
    return (
        ((parse_int(xer.get("so", 0)) & 1) << 31)
        | ((parse_int(xer.get("ov", 0)) & 1) << 30)
        | ((parse_int(xer.get("ca", 0)) & 1) << 29)
    )


def _uses_memory(case) -> int:
    if case.expected_memory or "memory" in case.initial:
        return 1
    if "memory" in case.tags or "update" in case.tags:
        return 1
    if case.id in {"stw-lbz-be", "lhz-be", "lha", "byte-reverse", "stwu", "lmw-stmw"}:
        return 1
    return 0


def generate_header() -> str:
    lines = [
        "/* Generated by tools/ppc_equivalence/gen_fixture_blob.py — do not edit. */",
        "#ifndef PPC_FIXTURE_CASES_INC",
        "#define PPC_FIXTURE_CASES_INC",
        "",
        f"#define PPC_FIXTURE_COUNT {len(FIXTURES)}",
        f"#define PPC_FIXTURE_CODE_MAX {CODE_MAX}",
        f"#define PPC_FIXTURE_MEM_WORDS {MEM_WORDS}",
        "",
        "typedef void (*PpcFixturePayloadFn)(void);",
        "",
        "typedef struct PpcFixtureCase {",
        f"    char name[{NAME_MAX + 1}];",
        "    u32 gpr[32];",
        "    u64 fpr[32];",
        "    u64 fpscr_image;",
        "    u32 cr;",
        "    u32 xer;",
        "    u32 lr;",
        "    u32 ctr;",
        f"    u32 mem[{MEM_WORDS}];",
        "    u32 uses_memory;",
        "    u32 result_reg;",
        "    u32 expected_result;",
        "    u32 expected_cr;",
        "    u32 expected_xer;",
        "    u32 expected_mem_count;",
        "    u32 expected_mem_off[8];",
        "    u32 expected_mem_val[8];",
        "    u32 expected_fpr_count;",
        "    u32 expected_fpr_index[8];",
        "    u64 expected_fpr_value[8];",
        "    u32 observe_fpscr;",
        "    u32 expected_fpscr;",
        "    PpcFixturePayloadFn payload;",
        "} PpcFixtureCase;",
        "",
    ]
    for index in range(len(FIXTURES)):
        lines.append(f"void ppc_fixture_payload_{index}(void);")
    lines.append("")
    lines.append("static const PpcFixtureCase g_ppc_fixtures[PPC_FIXTURE_COUNT] = {")

    for index, case in enumerate(FIXTURES):
        if len(case.code_words) > CODE_MAX:
            raise SystemExit(f"{case.id}: code length {len(case.code_words)} exceeds {CODE_MAX}")
        if len(case.id) > NAME_MAX:
            raise SystemExit(f"{case.id}: name longer than {NAME_MAX}")
        if len(case.expected_memory) > 8:
            raise SystemExit(f"{case.id}: too many expected memory words")
        if len(case.expected_fpr) > 8:
            raise SystemExit(f"{case.id}: too many expected FPRs")

        gpr = _gpr_array(case.initial)
        fpr = _fpr_array(case.initial)
        mem = _mem_words(case.initial)
        mem_offs = list(case.expected_memory.keys())
        mem_vals = [case.expected_memory[offset] for offset in mem_offs]
        mem_offs += [0] * (8 - len(mem_offs))
        mem_vals += [0] * (8 - len(mem_vals))
        fpr_indices = list(case.expected_fpr)
        fpr_values = [case.expected_fpr[index] for index in fpr_indices]
        fpr_indices += [0] * (8 - len(fpr_indices))
        fpr_values += [0] * (8 - len(fpr_values))

        lines.append("    {")
        lines.append(f"        {_c_string(case.id)},")
        lines.append("        {" + ", ".join(f"0x{value:08X}u" for value in gpr) + "},")
        lines.append("        {" + ", ".join(f"0x{value:016X}ull" for value in fpr) + "},")
        lines.append(f"        0x{parse_int(case.initial.get('fpscr', 0)):016X}ull,")
        lines.append(f"        0x{parse_int(case.initial.get('cr', 0)):08X}u,")
        lines.append(f"        0x{_xer_word(case.initial):08X}u,")
        lines.append(f"        0x{parse_int(case.initial.get('lr', 0)):08X}u,")
        lines.append(f"        0x{parse_int(case.initial.get('ctr', 0)):08X}u,")
        lines.append("        {" + ", ".join(f"0x{value:08X}u" for value in mem) + "},")
        lines.append(f"        {_uses_memory(case)}u,")
        lines.append(f"        {case.result_reg}u,")
        lines.append(f"        0x{case.expected_result:08X}u,")
        lines.append(f"        0x{case.expected_cr:08X}u,")
        lines.append(f"        0x{case.expected_xer:08X}u,")
        lines.append(f"        {len(case.expected_memory)}u,")
        lines.append("        {" + ", ".join(f"0x{value:X}u" for value in mem_offs) + "},")
        lines.append("        {" + ", ".join(f"0x{value:08X}u" for value in mem_vals) + "},")
        lines.append(f"        {len(case.expected_fpr)}u,")
        lines.append("        {" + ", ".join(f"{value}u" for value in fpr_indices) + "},")
        lines.append("        {" + ", ".join(f"0x{value:016X}ull" for value in fpr_values) + "},")
        lines.append(f"        {1 if case.expected_fpscr is not None else 0}u,")
        lines.append(f"        0x{(case.expected_fpscr or 0):08X}u,")
        lines.append(f"        ppc_fixture_payload_{index},")
        lines.append("    },")

    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def generate_payloads() -> str:
    lines = [
        "/* Generated by tools/ppc_equivalence/gen_fixture_blob.py — do not edit. */",
        "#include <types.h>",
        "",
        "/*",
        " * .text payloads for the generic fixture DOL. Words come from",
        " * tools/ppc_equivalence/fixtures/corpus.py.",
        " */",
        "",
    ]
    for index, case in enumerate(FIXTURES):
        lines.append(f"/* {case.id} */")
        lines.append(f"asm void ppc_fixture_payload_{index}(void) {{")
        lines.append("    nofralloc")
        for word in case.code_words:
            lines.append(f"    opword 0x{word & 0xFFFFFFFF:08X}")
        lines.append("    blr")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--payloads", type=Path, default=DEFAULT_PAYLOADS)
    parser.add_argument("--jsonl", type=Path, default=DEFAULT_JSONL)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    args = parser.parse_args()

    header = generate_header()
    payloads = generate_payloads()
    if args.check:
        current_header = args.header.read_text(encoding="utf-8") if args.header.is_file() else ""
        current_payloads = args.payloads.read_text(encoding="utf-8") if args.payloads.is_file() else ""
        if current_header != header or current_payloads != payloads:
            raise SystemExit(
                "generated fixture outputs are stale; run tools/ppc_equivalence/gen_fixture_blob.py"
            )
        export_jsonl(args.jsonl)
        return 0

    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(header, encoding="utf-8")
    args.payloads.write_text(payloads, encoding="utf-8")
    export_jsonl(args.jsonl)
    print(f"wrote {args.header}")
    print(f"wrote {args.payloads}")
    print(f"wrote {args.jsonl}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
