/* Generated by tools/ppc_equivalence/gen_fixture_blob.py — do not edit. */
#include <types.h>

/*
 * .text payloads for the generic fixture DOL. Words come from
 * tools/ppc_equivalence/fixtures/corpus.py.
 */

/* addc */
asm void ppc_fixture_payload_0(void) {
    nofralloc
    opword 0x7CE53015
    blr
}

/* addeo */
asm void ppc_fixture_payload_1(void) {
    nofralloc
    opword 0x7CE53515
    blr
}

/* addmeo */
asm void ppc_fixture_payload_2(void) {
    nofralloc
    opword 0x7CE505D5
    blr
}

/* subfc */
asm void ppc_fixture_payload_3(void) {
    nofralloc
    opword 0x7CE53011
    blr
}

/* subfeo */
asm void ppc_fixture_payload_4(void) {
    nofralloc
    opword 0x7CE53511
    blr
}

/* nego */
asm void ppc_fixture_payload_5(void) {
    nofralloc
    opword 0x7CE504D1
    blr
}

/* mulhw */
asm void ppc_fixture_payload_6(void) {
    nofralloc
    opword 0x7CE53097
    blr
}

/* mulhwu */
asm void ppc_fixture_payload_7(void) {
    nofralloc
    opword 0x7CE53017
    blr
}

/* mullwo */
asm void ppc_fixture_payload_8(void) {
    nofralloc
    opword 0x7CE535D7
    blr
}

/* divw */
asm void ppc_fixture_payload_9(void) {
    nofralloc
    opword 0x7CE533D7
    blr
}

/* divwu */
asm void ppc_fixture_payload_10(void) {
    nofralloc
    opword 0x7CE53397
    blr
}

/* slw31 */
asm void ppc_fixture_payload_11(void) {
    nofralloc
    opword 0x7CA73031
    blr
}

/* slw32 */
asm void ppc_fixture_payload_12(void) {
    nofralloc
    opword 0x7CA73031
    blr
}

/* srw */
asm void ppc_fixture_payload_13(void) {
    nofralloc
    opword 0x7CA73431
    blr
}

/* sraw */
asm void ppc_fixture_payload_14(void) {
    nofralloc
    opword 0x7CA73631
    blr
}

/* srawi */
asm void ppc_fixture_payload_15(void) {
    nofralloc
    opword 0x7CA70E71
    blr
}

/* rlwinm */
asm void ppc_fixture_payload_16(void) {
    nofralloc
    opword 0x54A7103B
    blr
}

/* rlwimi */
asm void ppc_fixture_payload_17(void) {
    nofralloc
    opword 0x50A7421F
    blr
}

/* rlwnm */
asm void ppc_fixture_payload_18(void) {
    nofralloc
    opword 0x5CA7303F
    blr
}

/* andc */
asm void ppc_fixture_payload_19(void) {
    nofralloc
    opword 0x7CA73079
    blr
}

/* eqv */
asm void ppc_fixture_payload_20(void) {
    nofralloc
    opword 0x7CA73239
    blr
}

/* nand */
asm void ppc_fixture_payload_21(void) {
    nofralloc
    opword 0x7CA733B9
    blr
}

/* nor */
asm void ppc_fixture_payload_22(void) {
    nofralloc
    opword 0x7CA730F9
    blr
}

/* orc */
asm void ppc_fixture_payload_23(void) {
    nofralloc
    opword 0x7CA73339
    blr
}

/* xor */
asm void ppc_fixture_payload_24(void) {
    nofralloc
    opword 0x7CA73279
    blr
}

/* extsb */
asm void ppc_fixture_payload_25(void) {
    nofralloc
    opword 0x7CA70775
    blr
}

/* extsh */
asm void ppc_fixture_payload_26(void) {
    nofralloc
    opword 0x7CA70735
    blr
}

/* cntlzw */
asm void ppc_fixture_payload_27(void) {
    nofralloc
    opword 0x7CA70035
    blr
}

/* cmpw */
asm void ppc_fixture_payload_28(void) {
    nofralloc
    opword 0x7C053000
    blr
}

/* cmplw */
asm void ppc_fixture_payload_29(void) {
    nofralloc
    opword 0x7C053040
    blr
}

/* cr-logical */
asm void ppc_fixture_payload_30(void) {
    nofralloc
    opword 0x4C011202
    opword 0x4C611342
    opword 0x4C811242
    opword 0x4CA11182
    opword 0x7CE00026
    blr
}

/* xer-transfer */
asm void ppc_fixture_payload_31(void) {
    nofralloc
    opword 0x7CA103A6
    opword 0x7CE102A6
    blr
}

/* stw-lbz-be */
asm void ppc_fixture_payload_32(void) {
    nofralloc
    opword 0x90A40000
    opword 0x88E40000
    blr
}

/* lhz-be */
asm void ppc_fixture_payload_33(void) {
    nofralloc
    opword 0xA0E40002
    blr
}

/* lha */
asm void ppc_fixture_payload_34(void) {
    nofralloc
    opword 0xB0A40004
    opword 0xA8E40004
    blr
}

/* byte-reverse */
asm void ppc_fixture_payload_35(void) {
    nofralloc
    opword 0x7CA4352C
    opword 0x7CE4342C
    blr
}

/* stwu */
asm void ppc_fixture_payload_36(void) {
    nofralloc
    opword 0x94AAFFFC
    opword 0x7CE45050
    blr
}

/* lmw-stmw */
asm void ppc_fixture_payload_37(void) {
    nofralloc
    opword 0xBB840010
    opword 0xBF840030
    opword 0x7F87EA78
    opword 0x7CE7F278
    opword 0x7CE7FA78
    blr
}

/* bc-cr */
asm void ppc_fixture_payload_38(void) {
    nofralloc
    opword 0x41800008
    opword 0x38E00001
    blr
}

/* bdnz */
asm void ppc_fixture_payload_39(void) {
    nofralloc
    opword 0x42000008
    opword 0x38E00001
    opword 0x54E7402E
    opword 0x7D0902A6
    opword 0x7CE74378
    blr
}

/* li */
asm void ppc_fixture_payload_40(void) {
    nofralloc
    opword 0x38E01234
    blr
}

/* addze */
asm void ppc_fixture_payload_41(void) {
    nofralloc
    opword 0x7CE50195
    blr
}

/* add-so-sticky */
asm void ppc_fixture_payload_42(void) {
    nofralloc
    opword 0x7CE53615
    blr
}

/* sraw32 */
asm void ppc_fixture_payload_43(void) {
    nofralloc
    opword 0x7CA73631
    blr
}

/* and. */
asm void ppc_fixture_payload_44(void) {
    nofralloc
    opword 0x7CA73039
    blr
}

/* cmpwi */
asm void ppc_fixture_payload_45(void) {
    nofralloc
    opword 0x2C050001
    blr
}

/* mtcrf-cr0 */
asm void ppc_fixture_payload_46(void) {
    nofralloc
    opword 0x7CA80120
    opword 0x7CE00026
    blr
}

/* lbzu */
asm void ppc_fixture_payload_47(void) {
    nofralloc
    opword 0x8D0A0001
    opword 0x7CE45050
    blr
}

/* lhbrx */
asm void ppc_fixture_payload_48(void) {
    nofralloc
    opword 0xB0A40008
    opword 0x7CE4362C
    blr
}

/* bc-cr-fallthrough */
asm void ppc_fixture_payload_49(void) {
    nofralloc
    opword 0x41800008
    opword 0x38E00001
    blr
}

/* subfze */
asm void ppc_fixture_payload_50(void) {
    nofralloc
    opword 0x7CE50191
    blr
}

/* addic */
asm void ppc_fixture_payload_51(void) {
    nofralloc
    opword 0x30E50001
    blr
}

/* addic-dot */
asm void ppc_fixture_payload_52(void) {
    nofralloc
    opword 0x34E50001
    blr
}

/* addis */
asm void ppc_fixture_payload_53(void) {
    nofralloc
    opword 0x3CE50001
    blr
}

/* andi-dot */
asm void ppc_fixture_payload_54(void) {
    nofralloc
    opword 0x70A700FF
    blr
}

/* andis-dot */
asm void ppc_fixture_payload_55(void) {
    nofralloc
    opword 0x74A700FF
    blr
}

/* cmplwi */
asm void ppc_fixture_payload_56(void) {
    nofralloc
    opword 0x28050001
    blr
}

/* mulli */
asm void ppc_fixture_payload_57(void) {
    nofralloc
    opword 0x1CE5FFFE
    blr
}

/* ori */
asm void ppc_fixture_payload_58(void) {
    nofralloc
    opword 0x60A70023
    blr
}

/* oris */
asm void ppc_fixture_payload_59(void) {
    nofralloc
    opword 0x64A70023
    blr
}

/* subfic */
asm void ppc_fixture_payload_60(void) {
    nofralloc
    opword 0x20E50000
    blr
}

/* subfme */
asm void ppc_fixture_payload_61(void) {
    nofralloc
    opword 0x7CE501D1
    blr
}

/* addme-carry-in */
asm void ppc_fixture_payload_62(void) {
    nofralloc
    opword 0x7CE501D5
    blr
}

/* subfme-carry-clear */
asm void ppc_fixture_payload_63(void) {
    nofralloc
    opword 0x7CE501D1
    blr
}

/* xori */
asm void ppc_fixture_payload_64(void) {
    nofralloc
    opword 0x68A700FF
    blr
}

/* xoris */
asm void ppc_fixture_payload_65(void) {
    nofralloc
    opword 0x6CA700FF
    blr
}

/* crandc */
asm void ppc_fixture_payload_66(void) {
    nofralloc
    opword 0x4C400902
    opword 0x7CE00026
    blr
}

/* crnand */
asm void ppc_fixture_payload_67(void) {
    nofralloc
    opword 0x4C4009C2
    opword 0x7CE00026
    blr
}

/* crnor */
asm void ppc_fixture_payload_68(void) {
    nofralloc
    opword 0x4C400842
    opword 0x7CE00026
    blr
}

/* cror */
asm void ppc_fixture_payload_69(void) {
    nofralloc
    opword 0x4C400B82
    opword 0x7CE00026
    blr
}

/* b-direct */
asm void ppc_fixture_payload_70(void) {
    nofralloc
    opword 0x48000008
    opword 0x38E00001
    opword 0x38E00002
    blr
}

/* bclr-not-taken */
asm void ppc_fixture_payload_71(void) {
    nofralloc
    opword 0x4D800020
    opword 0x38E00001
    blr
}

/* bcctr-not-taken */
asm void ppc_fixture_payload_72(void) {
    nofralloc
    opword 0x4D800420
    opword 0x38E00001
    blr
}

/* lwz */
asm void ppc_fixture_payload_73(void) {
    nofralloc
    opword 0x80E40004
    blr
}

/* lwzu */
asm void ppc_fixture_payload_74(void) {
    nofralloc
    opword 0x84E40004
    blr
}

/* lbzx */
asm void ppc_fixture_payload_75(void) {
    nofralloc
    opword 0x7CE430AE
    blr
}

/* lbzux */
asm void ppc_fixture_payload_76(void) {
    nofralloc
    opword 0x7CE430EE
    blr
}

/* lhzu */
asm void ppc_fixture_payload_77(void) {
    nofralloc
    opword 0xA4E40002
    blr
}

/* lhau */
asm void ppc_fixture_payload_78(void) {
    nofralloc
    opword 0xACE40002
    blr
}

/* lhzx */
asm void ppc_fixture_payload_79(void) {
    nofralloc
    opword 0x7CE4322E
    blr
}

/* lhzux */
asm void ppc_fixture_payload_80(void) {
    nofralloc
    opword 0x7CE4326E
    blr
}

/* lhax */
asm void ppc_fixture_payload_81(void) {
    nofralloc
    opword 0x7CE432AE
    blr
}

/* lhaux */
asm void ppc_fixture_payload_82(void) {
    nofralloc
    opword 0x7CE432EE
    blr
}

/* lwzx */
asm void ppc_fixture_payload_83(void) {
    nofralloc
    opword 0x7CE4302E
    blr
}

/* lwzux */
asm void ppc_fixture_payload_84(void) {
    nofralloc
    opword 0x7CE4306E
    blr
}

/* stb */
asm void ppc_fixture_payload_85(void) {
    nofralloc
    opword 0x98A40001
    blr
}

/* stbu */
asm void ppc_fixture_payload_86(void) {
    nofralloc
    opword 0x9CA40001
    blr
}

/* stbx */
asm void ppc_fixture_payload_87(void) {
    nofralloc
    opword 0x7CA431AE
    blr
}

/* stbux */
asm void ppc_fixture_payload_88(void) {
    nofralloc
    opword 0x7CA431EE
    blr
}

/* sthu */
asm void ppc_fixture_payload_89(void) {
    nofralloc
    opword 0xB4A40002
    blr
}

/* sthx */
asm void ppc_fixture_payload_90(void) {
    nofralloc
    opword 0x7CA4332E
    blr
}

/* sthux */
asm void ppc_fixture_payload_91(void) {
    nofralloc
    opword 0x7CA4336E
    blr
}

/* sthbrx */
asm void ppc_fixture_payload_92(void) {
    nofralloc
    opword 0x7CA4372C
    blr
}

/* stwx */
asm void ppc_fixture_payload_93(void) {
    nofralloc
    opword 0x7CA4312E
    blr
}

/* stwux */
asm void ppc_fixture_payload_94(void) {
    nofralloc
    opword 0x7CA4316E
    blr
}

/* mffs */
asm void ppc_fixture_payload_95(void) {
    nofralloc
    opword 0xFCE0048E
    blr
}

/* mtfsf */
asm void ppc_fixture_payload_96(void) {
    nofralloc
    opword 0xFDFE158F
    blr
}

/* mtfsfi */
asm void ppc_fixture_payload_97(void) {
    nofralloc
    opword 0xFF80310C
    blr
}

/* mtfsb1 */
asm void ppc_fixture_payload_98(void) {
    nofralloc
    opword 0xFD60004C
    blr
}

/* mtfsb0 */
asm void ppc_fixture_payload_99(void) {
    nofralloc
    opword 0xFD60008C
    blr
}

/* mcrfs */
asm void ppc_fixture_payload_100(void) {
    nofralloc
    opword 0xFD880080
    blr
}

/* ps_neg */
asm void ppc_fixture_payload_101(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E00851
    opword 0xF0E41010
    blr
}

/* ps_mr */
asm void ppc_fixture_payload_102(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E00890
    opword 0xF0E41010
    blr
}

/* ps_nabs */
asm void ppc_fixture_payload_103(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E00910
    opword 0xF0E41010
    blr
}

/* ps_abs */
asm void ppc_fixture_payload_104(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E00A10
    opword 0xF0E41010
    blr
}

/* ps_merge00 */
asm void ppc_fixture_payload_105(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E11420
    opword 0xF0E41010
    blr
}

/* ps_merge01 */
asm void ppc_fixture_payload_106(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E11460
    opword 0xF0E41010
    blr
}

/* ps_merge10 */
asm void ppc_fixture_payload_107(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E114A0
    opword 0xF0E41010
    blr
}

/* ps_merge11 */
asm void ppc_fixture_payload_108(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E114E0
    opword 0xF0E41010
    blr
}

/* ps_cmpu0 */
asm void ppc_fixture_payload_109(void) {
    nofralloc
    opword 0x11811000
    blr
}

/* ps_cmpo0 */
asm void ppc_fixture_payload_110(void) {
    nofralloc
    opword 0x11811040
    blr
}

/* ps_cmpu1 */
asm void ppc_fixture_payload_111(void) {
    nofralloc
    opword 0x10620C20
    opword 0x10821420
    opword 0x11832080
    blr
}

/* ps_cmpo1 */
asm void ppc_fixture_payload_112(void) {
    nofralloc
    opword 0x10620C20
    opword 0x10821420
    opword 0x118320C0
    blr
}

/* ps_add */
asm void ppc_fixture_payload_113(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E1102B
    opword 0xF0E41010
    blr
}

/* ps_sub */
asm void ppc_fixture_payload_114(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E11028
    opword 0xF0E41010
    blr
}

/* ps_mul */
asm void ppc_fixture_payload_115(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E100B2
    opword 0xF0E41010
    blr
}

/* ps_muls0 */
asm void ppc_fixture_payload_116(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E10098
    opword 0xF0E41010
    blr
}

/* ps_muls1 */
asm void ppc_fixture_payload_117(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0x10E1009A
    opword 0xF0E41010
    blr
}

/* ps_mul-force25 */
asm void ppc_fixture_payload_118(void) {
    nofralloc
    opword 0x10210C20
    opword 0x10631C20
    opword 0x10E100F2
    blr
}

/* ps_add-lane-exceptions */
asm void ppc_fixture_payload_119(void) {
    nofralloc
    opword 0x10A11C20
    opword 0x10C22420
    opword 0x10E5302B
    blr
}

/* ps_add-ve-writes */
asm void ppc_fixture_payload_120(void) {
    nofralloc
    opword 0x10A11420
    opword 0x10C32420
    opword 0x10E5302A
    blr
}

/* ps_mul-vximz-ps1 */
asm void ppc_fixture_payload_121(void) {
    nofralloc
    opword 0x10A11420
    opword 0x10C32420
    opword 0x10E501B2
    blr
}

/* ps_madd */
asm void ppc_fixture_payload_122(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110FB
    opword 0xF0E41018
    blr
}

/* ps_msub */
asm void ppc_fixture_payload_123(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110F8
    opword 0xF0E41018
    blr
}

/* ps_nmadd */
asm void ppc_fixture_payload_124(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110FE
    opword 0xF0E41018
    blr
}

/* ps_nmsub */
asm void ppc_fixture_payload_125(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110FC
    opword 0xF0E41018
    blr
}

/* ps_madds0 */
asm void ppc_fixture_payload_126(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110DC
    opword 0xF0E41018
    blr
}

/* ps_madds1 */
asm void ppc_fixture_payload_127(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110DE
    opword 0xF0E41018
    blr
}

/* ps_nmadd-lane-invalid-ve */
asm void ppc_fixture_payload_128(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10A11420
    opword 0x10C32420
    opword 0x11484C20
    opword 0x10E532BE
    opword 0xF0E41000
    blr
}

/* ps_sum0 */
asm void ppc_fixture_payload_129(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110D4
    opword 0xF0E41018
    blr
}

/* ps_sum1 */
asm void ppc_fixture_payload_130(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110D7
    opword 0xF0E41018
    blr
}

/* ps_sum0-vxisi */
asm void ppc_fixture_payload_131(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10A10C20
    opword 0x10C21420
    opword 0x11031C20
    opword 0x10E53214
    opword 0xF0E41000
    blr
}

/* ps_sel-signed-zero-nan */
asm void ppc_fixture_payload_132(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0241000
    opword 0xE0441008
    opword 0xE0641010
    opword 0x10E110EF
    opword 0xF0E41018
    blr
}

/* psq-l-st-quantized */
asm void ppc_fixture_payload_133(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0E41000
    opword 0xF0E41008
    blr
}

/* psq-u8-load-s8-store */
asm void ppc_fixture_payload_134(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0E41000
    opword 0xF0E41004
    blr
}

/* psq-u16-load-float-store */
asm void ppc_fixture_payload_135(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE0E41000
    opword 0xF0E41008
    blr
}

/* psq-st-float-ftz */
asm void ppc_fixture_payload_136(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xF0E49000
    blr
}

/* psq-lu-w1 */
asm void ppc_fixture_payload_137(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xE4E49004
    blr
}

/* psq-stu-w1 */
asm void ppc_fixture_payload_138(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0xF4E49004
    blr
}

/* psq-lx-s16 */
asm void ppc_fixture_payload_139(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10E4308C
    blr
}

/* psq-lux-s8 */
asm void ppc_fixture_payload_140(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10E430CC
    blr
}

/* psq-stx-u16 */
asm void ppc_fixture_payload_141(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10E4348E
    blr
}

/* psq-stux-s16 */
asm void ppc_fixture_payload_142(void) {
    nofralloc
    opword 0x7CB1E3A6
    opword 0x10E434CE
    blr
}

/* lfs */
asm void ppc_fixture_payload_143(void) {
    nofralloc
    opword 0xC0E40000
    blr
}

/* lfsu */
asm void ppc_fixture_payload_144(void) {
    nofralloc
    opword 0xC4E40004
    blr
}

/* lfd */
asm void ppc_fixture_payload_145(void) {
    nofralloc
    opword 0xC8E40000
    blr
}

/* lfdu */
asm void ppc_fixture_payload_146(void) {
    nofralloc
    opword 0xCCE40008
    blr
}

/* stfs */
asm void ppc_fixture_payload_147(void) {
    nofralloc
    opword 0xD0A40000
    blr
}

/* stfsu */
asm void ppc_fixture_payload_148(void) {
    nofralloc
    opword 0xD4A40004
    blr
}

/* stfd */
asm void ppc_fixture_payload_149(void) {
    nofralloc
    opword 0xD8A40000
    blr
}

/* stfdu */
asm void ppc_fixture_payload_150(void) {
    nofralloc
    opword 0xDCA40008
    blr
}

/* lfsx */
asm void ppc_fixture_payload_151(void) {
    nofralloc
    opword 0x7CE4342E
    blr
}

/* lfsux */
asm void ppc_fixture_payload_152(void) {
    nofralloc
    opword 0x7CE4346E
    blr
}

/* lfdx */
asm void ppc_fixture_payload_153(void) {
    nofralloc
    opword 0x7CE434AE
    blr
}

/* lfdux */
asm void ppc_fixture_payload_154(void) {
    nofralloc
    opword 0x7CE434EE
    blr
}

/* stfsx */
asm void ppc_fixture_payload_155(void) {
    nofralloc
    opword 0x7CA4352E
    blr
}

/* stfsux */
asm void ppc_fixture_payload_156(void) {
    nofralloc
    opword 0x7CA4356E
    blr
}

/* stfdx */
asm void ppc_fixture_payload_157(void) {
    nofralloc
    opword 0x7CA435AE
    blr
}

/* stfdux */
asm void ppc_fixture_payload_158(void) {
    nofralloc
    opword 0x7CA435EE
    blr
}

/* stfiwx */
asm void ppc_fixture_payload_159(void) {
    nofralloc
    opword 0x7CA437AE
    blr
}

/* fadds */
asm void ppc_fixture_payload_160(void) {
    nofralloc
    opword 0xECE1102B
    blr
}

/* fsubs */
asm void ppc_fixture_payload_161(void) {
    nofralloc
    opword 0xECE11028
    blr
}

/* fmuls */
asm void ppc_fixture_payload_162(void) {
    nofralloc
    opword 0xECE100F3
    blr
}

/* fmuls-force25 */
asm void ppc_fixture_payload_163(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

/* fmuls-force25-subnormal */
asm void ppc_fixture_payload_164(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

/* fdivs */
asm void ppc_fixture_payload_165(void) {
    nofralloc
    opword 0xECE11024
    blr
}

/* fadd */
asm void ppc_fixture_payload_166(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

/* fsub */
asm void ppc_fixture_payload_167(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

/* fmul */
asm void ppc_fixture_payload_168(void) {
    nofralloc
    opword 0xFCE100F2
    blr
}

/* fdiv */
asm void ppc_fixture_payload_169(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

/* fadd-vxisi */
asm void ppc_fixture_payload_170(void) {
    nofralloc
    opword 0xFCE1102B
    blr
}

/* fadd-vxisi-ve */
asm void ppc_fixture_payload_171(void) {
    nofralloc
    opword 0xFCE1102B
    blr
}

/* fadds-snan */
asm void ppc_fixture_payload_172(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

/* fadds-snan-ve */
asm void ppc_fixture_payload_173(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

/* fadd-qnan */
asm void ppc_fixture_payload_174(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

/* fsub-vxisi */
asm void ppc_fixture_payload_175(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

/* fmul-vximz */
asm void ppc_fixture_payload_176(void) {
    nofralloc
    opword 0xFCE100F2
    blr
}

/* fmuls-vximz */
asm void ppc_fixture_payload_177(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

/* fdiv-vxzdz */
asm void ppc_fixture_payload_178(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

/* fdiv-vxidi */
asm void ppc_fixture_payload_179(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

/* fdiv-zx */
asm void ppc_fixture_payload_180(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

/* fdiv-zx-ze */
asm void ppc_fixture_payload_181(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

/* fdivs-zx */
asm void ppc_fixture_payload_182(void) {
    nofralloc
    opword 0xECE11024
    blr
}

/* fdivs-zx-ze */
asm void ppc_fixture_payload_183(void) {
    nofralloc
    opword 0xECE11024
    blr
}

/* fctiw-rne-away */
asm void ppc_fixture_payload_184(void) {
    nofralloc
    opword 0xFCE0101D
    blr
}

/* fctiw-rne-even */
asm void ppc_fixture_payload_185(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-rtz */
asm void ppc_fixture_payload_186(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-rtp */
asm void ppc_fixture_payload_187(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-rtn */
asm void ppc_fixture_payload_188(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiwz-negative-zero-result */
asm void ppc_fixture_payload_189(void) {
    nofralloc
    opword 0xFCE0101E
    blr
}

/* fctiw-exact-clears-fifr */
asm void ppc_fixture_payload_190(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-negative-zero */
asm void ppc_fixture_payload_191(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-qnan */
asm void ppc_fixture_payload_192(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-snan */
asm void ppc_fixture_payload_193(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-positive-overflow */
asm void ppc_fixture_payload_194(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-negative-overflow */
asm void ppc_fixture_payload_195(void) {
    nofralloc
    opword 0xFCE0101C
    blr
}

/* fctiw-ve */
asm void ppc_fixture_payload_196(void) {
    nofralloc
    opword 0xFCE0101D
    blr
}

/* fctiw-xe */
asm void ppc_fixture_payload_197(void) {
    nofralloc
    opword 0xFCE0101D
    blr
}

/* fmadds */
asm void ppc_fixture_payload_198(void) {
    nofralloc
    opword 0xECE110FB
    blr
}

/* fmadds-force25 */
asm void ppc_fixture_payload_199(void) {
    nofralloc
    opword 0xECE110FA
    blr
}

/* fmadds-single-rounding */
asm void ppc_fixture_payload_200(void) {
    nofralloc
    opword 0xECE110FA
    blr
}

/* fmadds-nan-order */
asm void ppc_fixture_payload_201(void) {
    nofralloc
    opword 0xECE110FA
    blr
}

/* fmadds-vximz */
asm void ppc_fixture_payload_202(void) {
    nofralloc
    opword 0xECE110FA
    blr
}

/* fmadds-vximz-ve */
asm void ppc_fixture_payload_203(void) {
    nofralloc
    opword 0xECE110FB
    blr
}

/* fmadds-vxisi */
asm void ppc_fixture_payload_204(void) {
    nofralloc
    opword 0xECE110FA
    blr
}

/* fmsubs */
asm void ppc_fixture_payload_205(void) {
    nofralloc
    opword 0xECE110F8
    blr
}

/* fnmsubs */
asm void ppc_fixture_payload_206(void) {
    nofralloc
    opword 0xECE110FC
    blr
}

/* fmsubs-positive-zero */
asm void ppc_fixture_payload_207(void) {
    nofralloc
    opword 0xECE110F8
    blr
}

/* fnmsubs-negative-zero */
asm void ppc_fixture_payload_208(void) {
    nofralloc
    opword 0xECE110FC
    blr
}

/* fmsubs-single-rounding */
asm void ppc_fixture_payload_209(void) {
    nofralloc
    opword 0xECE110F8
    blr
}

/* fnmsubs-single-rounding */
asm void ppc_fixture_payload_210(void) {
    nofralloc
    opword 0xECE110FC
    blr
}

/* fnmsubs-nan-not-negated */
asm void ppc_fixture_payload_211(void) {
    nofralloc
    opword 0xECE110FC
    blr
}

/* fmsubs-vxisi */
asm void ppc_fixture_payload_212(void) {
    nofralloc
    opword 0xECE110F8
    blr
}

/* fnmsubs-vximz */
asm void ppc_fixture_payload_213(void) {
    nofralloc
    opword 0xECE110FC
    blr
}

/* fnmsubs-vxisi-ve */
asm void ppc_fixture_payload_214(void) {
    nofralloc
    opword 0xECE110FD
    blr
}

/* fnmadds */
asm void ppc_fixture_payload_215(void) {
    nofralloc
    opword 0xECE110FE
    blr
}

/* fnmadds-nan-not-negated */
asm void ppc_fixture_payload_216(void) {
    nofralloc
    opword 0xECE110FE
    blr
}

/* fmadd */
asm void ppc_fixture_payload_217(void) {
    nofralloc
    opword 0xFCE110FA
    blr
}

/* fmadd-single-rounding */
asm void ppc_fixture_payload_218(void) {
    nofralloc
    opword 0xFCE110FA
    blr
}

/* fmadd-nan-payload */
asm void ppc_fixture_payload_219(void) {
    nofralloc
    opword 0xFCE110FA
    blr
}

/* fmsub */
asm void ppc_fixture_payload_220(void) {
    nofralloc
    opword 0xFCE110F8
    blr
}

/* fnmadd */
asm void ppc_fixture_payload_221(void) {
    nofralloc
    opword 0xFCE110FE
    blr
}

/* fnmadd-vxisi-ve */
asm void ppc_fixture_payload_222(void) {
    nofralloc
    opword 0xFCE110FF
    blr
}

/* fnmsub */
asm void ppc_fixture_payload_223(void) {
    nofralloc
    opword 0xFCE110FC
    blr
}

/* fnmsub-vximz */
asm void ppc_fixture_payload_224(void) {
    nofralloc
    opword 0xFCE110FC
    blr
}

/* fsel */
asm void ppc_fixture_payload_225(void) {
    nofralloc
    opword 0xFCE110EE
    blr
}

/* fcmpu */
asm void ppc_fixture_payload_226(void) {
    nofralloc
    opword 0xFC011000
    blr
}

/* fcmpu-snan */
asm void ppc_fixture_payload_227(void) {
    nofralloc
    opword 0xFD811000
    blr
}

/* fcmpo */
asm void ppc_fixture_payload_228(void) {
    nofralloc
    opword 0xFD811040
    blr
}

/* fcmpo-qnan */
asm void ppc_fixture_payload_229(void) {
    nofralloc
    opword 0xFD811040
    blr
}

/* fcmpo-qnan-ve */
asm void ppc_fixture_payload_230(void) {
    nofralloc
    opword 0xFD811040
    blr
}

/* fcmpo-snan */
asm void ppc_fixture_payload_231(void) {
    nofralloc
    opword 0xFD811040
    blr
}

/* fcmpo-snan-ve */
asm void ppc_fixture_payload_232(void) {
    nofralloc
    opword 0xFD811040
    blr
}

/* frsp */
asm void ppc_fixture_payload_233(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

/* fneg */
asm void ppc_fixture_payload_234(void) {
    nofralloc
    opword 0xFCE01050
    blr
}

/* fmr */
asm void ppc_fixture_payload_235(void) {
    nofralloc
    opword 0xFCE01090
    blr
}

/* fnabs */
asm void ppc_fixture_payload_236(void) {
    nofralloc
    opword 0xFCE01110
    blr
}

/* fabs */
asm void ppc_fixture_payload_237(void) {
    nofralloc
    opword 0xFCE01210
    blr
}
