/* Generated by tools/ppc_equivalence/gen_fixture_blob.py — do not edit. */
#include <types.h>

/*
 * .text payloads for the generic fixture DOL. Words come from
 * tools/ppc_equivalence/fixtures/corpus.py.
 */

/* addc */
asm void ppc_fixture_payload_0(void) {
    nofralloc
    opword 0x7CE53015
    blr
}

/* addeo */
asm void ppc_fixture_payload_1(void) {
    nofralloc
    opword 0x7CE53515
    blr
}

/* addmeo */
asm void ppc_fixture_payload_2(void) {
    nofralloc
    opword 0x7CE505D5
    blr
}

/* subfc */
asm void ppc_fixture_payload_3(void) {
    nofralloc
    opword 0x7CE53011
    blr
}

/* subfeo */
asm void ppc_fixture_payload_4(void) {
    nofralloc
    opword 0x7CE53511
    blr
}

/* nego */
asm void ppc_fixture_payload_5(void) {
    nofralloc
    opword 0x7CE504D1
    blr
}

/* mulhw */
asm void ppc_fixture_payload_6(void) {
    nofralloc
    opword 0x7CE53097
    blr
}

/* mulhwu */
asm void ppc_fixture_payload_7(void) {
    nofralloc
    opword 0x7CE53017
    blr
}

/* mullwo */
asm void ppc_fixture_payload_8(void) {
    nofralloc
    opword 0x7CE535D7
    blr
}

/* divw */
asm void ppc_fixture_payload_9(void) {
    nofralloc
    opword 0x7CE533D7
    blr
}

/* divwu */
asm void ppc_fixture_payload_10(void) {
    nofralloc
    opword 0x7CE53397
    blr
}

/* slw31 */
asm void ppc_fixture_payload_11(void) {
    nofralloc
    opword 0x7CA73031
    blr
}

/* slw32 */
asm void ppc_fixture_payload_12(void) {
    nofralloc
    opword 0x7CA73031
    blr
}

/* srw */
asm void ppc_fixture_payload_13(void) {
    nofralloc
    opword 0x7CA73431
    blr
}

/* sraw */
asm void ppc_fixture_payload_14(void) {
    nofralloc
    opword 0x7CA73631
    blr
}

/* srawi */
asm void ppc_fixture_payload_15(void) {
    nofralloc
    opword 0x7CA70E71
    blr
}

/* rlwinm */
asm void ppc_fixture_payload_16(void) {
    nofralloc
    opword 0x54A7103B
    blr
}

/* rlwimi */
asm void ppc_fixture_payload_17(void) {
    nofralloc
    opword 0x50A7421F
    blr
}

/* rlwnm */
asm void ppc_fixture_payload_18(void) {
    nofralloc
    opword 0x5CA7303F
    blr
}

/* andc */
asm void ppc_fixture_payload_19(void) {
    nofralloc
    opword 0x7CA73079
    blr
}

/* eqv */
asm void ppc_fixture_payload_20(void) {
    nofralloc
    opword 0x7CA73239
    blr
}

/* nand */
asm void ppc_fixture_payload_21(void) {
    nofralloc
    opword 0x7CA733B9
    blr
}

/* nor */
asm void ppc_fixture_payload_22(void) {
    nofralloc
    opword 0x7CA730F9
    blr
}

/* orc */
asm void ppc_fixture_payload_23(void) {
    nofralloc
    opword 0x7CA73339
    blr
}

/* xor */
asm void ppc_fixture_payload_24(void) {
    nofralloc
    opword 0x7CA73279
    blr
}

/* extsb */
asm void ppc_fixture_payload_25(void) {
    nofralloc
    opword 0x7CA70775
    blr
}

/* extsh */
asm void ppc_fixture_payload_26(void) {
    nofralloc
    opword 0x7CA70735
    blr
}

/* cntlzw */
asm void ppc_fixture_payload_27(void) {
    nofralloc
    opword 0x7CA70035
    blr
}

/* cmpw */
asm void ppc_fixture_payload_28(void) {
    nofralloc
    opword 0x7C053000
    blr
}

/* cmplw */
asm void ppc_fixture_payload_29(void) {
    nofralloc
    opword 0x7C053040
    blr
}

/* cr-logical */
asm void ppc_fixture_payload_30(void) {
    nofralloc
    opword 0x4C011202
    opword 0x4C611342
    opword 0x4C811242
    opword 0x4CA11182
    opword 0x7CE00026
    blr
}

/* xer-transfer */
asm void ppc_fixture_payload_31(void) {
    nofralloc
    opword 0x7CA103A6
    opword 0x7CE102A6
    blr
}

/* stw-lbz-be */
asm void ppc_fixture_payload_32(void) {
    nofralloc
    opword 0x90A40000
    opword 0x88E40000
    blr
}

/* lhz-be */
asm void ppc_fixture_payload_33(void) {
    nofralloc
    opword 0xA0E40002
    blr
}

/* lha */
asm void ppc_fixture_payload_34(void) {
    nofralloc
    opword 0xB0A40004
    opword 0xA8E40004
    blr
}

/* byte-reverse */
asm void ppc_fixture_payload_35(void) {
    nofralloc
    opword 0x7CA4352C
    opword 0x7CE4342C
    blr
}

/* stwu */
asm void ppc_fixture_payload_36(void) {
    nofralloc
    opword 0x94AAFFFC
    opword 0x7CE45050
    blr
}

/* lmw-stmw */
asm void ppc_fixture_payload_37(void) {
    nofralloc
    opword 0xBB840010
    opword 0xBF840030
    opword 0x7F87EA78
    opword 0x7CE7F278
    opword 0x7CE7FA78
    blr
}

/* bc-cr */
asm void ppc_fixture_payload_38(void) {
    nofralloc
    opword 0x41800008
    opword 0x38E00001
    blr
}

/* bdnz */
asm void ppc_fixture_payload_39(void) {
    nofralloc
    opword 0x42000008
    opword 0x38E00001
    opword 0x54E7402E
    opword 0x7D0902A6
    opword 0x7CE74378
    blr
}

/* li */
asm void ppc_fixture_payload_40(void) {
    nofralloc
    opword 0x38E01234
    blr
}

/* addze */
asm void ppc_fixture_payload_41(void) {
    nofralloc
    opword 0x7CE50195
    blr
}

/* add-so-sticky */
asm void ppc_fixture_payload_42(void) {
    nofralloc
    opword 0x7CE53615
    blr
}

/* sraw32 */
asm void ppc_fixture_payload_43(void) {
    nofralloc
    opword 0x7CA73631
    blr
}

/* and. */
asm void ppc_fixture_payload_44(void) {
    nofralloc
    opword 0x7CA73039
    blr
}

/* cmpwi */
asm void ppc_fixture_payload_45(void) {
    nofralloc
    opword 0x2C050001
    blr
}

/* mtcrf-cr0 */
asm void ppc_fixture_payload_46(void) {
    nofralloc
    opword 0x7CA80120
    opword 0x7CE00026
    blr
}

/* lbzu */
asm void ppc_fixture_payload_47(void) {
    nofralloc
    opword 0x8D0A0001
    opword 0x7CE45050
    blr
}

/* lhbrx */
asm void ppc_fixture_payload_48(void) {
    nofralloc
    opword 0xB0A40008
    opword 0x7CE4362C
    blr
}

/* bc-cr-fallthrough */
asm void ppc_fixture_payload_49(void) {
    nofralloc
    opword 0x41800008
    opword 0x38E00001
    blr
}

/* subfze */
asm void ppc_fixture_payload_50(void) {
    nofralloc
    opword 0x7CE50191
    blr
}
