/* Generated by tools/ppc_equivalence/scalar_fp_v2_capture.py --gen */
#include <types.h>

asm void scalar_fp_v2_capture_payload_0(void) {
    nofralloc
    opword 0xFC011000
    blr
}

asm void scalar_fp_v2_capture_payload_1(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_2(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_3(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_4(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_5(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_6(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_7(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_8(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_9(void) {
    nofralloc
    opword 0xFCE01018
    blr
}

asm void scalar_fp_v2_capture_payload_10(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_11(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_12(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_13(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_14(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_15(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_16(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_17(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_18(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_19(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_20(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_21(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_22(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_23(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_24(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_25(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_26(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_27(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_28(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_29(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_30(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_31(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_32(void) {
    nofralloc
    opword 0xFCE100F2
    blr
}

asm void scalar_fp_v2_capture_payload_33(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

asm void scalar_fp_v2_capture_payload_34(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

asm void scalar_fp_v2_capture_payload_35(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_36(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_37(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_38(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_39(void) {
    nofralloc
    opword 0xECE100F2
    blr
}

asm void scalar_fp_v2_capture_payload_40(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_41(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_42(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_43(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_44(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_45(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_46(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_47(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_48(void) {
    nofralloc
    opword 0xFCE11028
    blr
}

asm void scalar_fp_v2_capture_payload_49(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_50(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_51(void) {
    nofralloc
    opword 0xECE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_52(void) {
    nofralloc
    opword 0xFCE11024
    blr
}

asm void scalar_fp_v2_capture_payload_53(void) {
    nofralloc
    opword 0xFCE1102A
    blr
}

asm void scalar_fp_v2_capture_payload_54(void) {
    nofralloc
    opword 0xFCE11028
    blr
}
