// Anchor for the TU; the real .sdata2 touch lives at the bottom
// (dummy must see the label declarations first).
extern "C" void dummy();

// Typified retail data (replaces the old generated byte blobs). Layout from
// build/us/asm/kyoshin/cf/CfGimmickEne.s.

// .rodata 0x58: type string + BDAT column-name blob.
__declspec(section ".rodata") __attribute__((used))
const char lbl_eu_8050E690[0x14] = "cf::CfGimmickEne";
__declspec(section ".rodata") __attribute__((used))
const char lbl_eu_8050E6A4[0x44] =
    "eneID\0artID\0state\0EFF\0SE\0envSE\0wet\0hour\0spWF\0startF\0watiF\0endF";

// .sdata2 0x48: short tags (with retail padding) then float pool.
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668948[8] = "aLOD1";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668950[8] = "aType";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668958[8] = "aSpd";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668960[4] = "aCL";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668964[4] = "cl1";
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668968 = 1.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066896C = 0.0f;
__declspec(section ".sdata2") __attribute__((used))
const int lbl_eu_80668970 = -1;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668974 = -100.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668978 = 100.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066897C = 0.01f;
__declspec(section ".sdata2") __attribute__((used))
const double lbl_eu_80668980 = 4503599627370496.0;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668988 = 255.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066898C = 0.1f;

// .sdata 0x28: RTTI-ish pointer pairs (reloc sites are zero bytes in .o).
extern char lbl_eu_8050DBC4[];
extern char lbl_eu_805379F0[];
extern char lbl_eu_8050DBD8[];
extern char lbl_eu_8050DBF0[];
extern char lbl_eu_8050DC08[];
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_80662990[2] = { lbl_eu_8050DBC4, lbl_eu_805379F0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_80662998[2] = { lbl_eu_8050DBD8, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629A0[2] = { lbl_eu_8050DBF0, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629A8[2] = { lbl_eu_8050DC08, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629B0[2] = { lbl_eu_80668964, 0 };

// .data 0x7C: dtor-descriptor triples, dispatch rows, tag-pointer table.
extern "C" {
void __dt__Q22UI17CPassiveSkillLineFv();
void __dt__Q22UI17CPassiveSkillInfoFv();
void __dt__Q22UI16CPassiveSkillCurFv();
void func_8026EA20();
void func_8026EBA8();
void func_8026EC80();
void func_8026ECEC();
void func_8026F254();
void func_8026F31C();
}
struct EneTagTrio {
    const void* a;
    const void* b;
    const void* c;
};
struct EneDataRow {
    const void* a;
    unsigned int b;
    const void* c;
};
// NOTE: MWCC 8-aligns .data objects whose size is a multiple of 8, so
// retail's packed layout needs every object sized off the 8-grid: single
// 12-byte rows (not one 72-byte table) and a 12+4 split for the tags.
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_805379FC = {
    lbl_eu_80662998, 0, (const void*)__dt__Q22UI17CPassiveSkillLineFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A08 = {
    lbl_eu_806629A0, 0, (const void*)__dt__Q22UI17CPassiveSkillInfoFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A14 = {
    lbl_eu_806629A8, 0, (const void*)__dt__Q22UI16CPassiveSkillCurFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A20 = { 0, 0xFFFFFFFFu, (const void*)func_8026EA20 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow1 = { 0, 0xFFFFFFFFu, (const void*)func_8026EBA8 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow2 = { 0, 0xFFFFFFFFu, (const void*)func_8026EC80 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow3 = { 0, 0xFFFFFFFFu, (const void*)func_8026ECEC };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow4 = { 0, 0xFFFFFFFFu, (const void*)func_8026F254 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow5 = { 0, 0xFFFFFFFFu, (const void*)func_8026F31C };
__declspec(section ".data") __attribute__((used))
const EneTagTrio lbl_eu_80537A68 = { lbl_eu_80668948, lbl_eu_80668950, lbl_eu_80668958 };
__declspec(section ".data") __attribute__((used))
static const void* s_tagD = lbl_eu_80668960;

extern "C" void dummy() {
    // Anchor the .sdata2 scalar pool above: MWCC drops unreferenced const
    // scalars, so volatile-read each label in retail order (emission =
    // first use). Plain arithmetic folds at compile time and drops the
    // labels, so every read goes through a volatile pointer.
    volatile float sinkf;
    sinkf = *(volatile float*)&lbl_eu_80668968;
    sinkf = *(volatile float*)&lbl_eu_8066896C;
    volatile int sinki = *(volatile int*)&lbl_eu_80668970;
    sinkf = *(volatile float*)&lbl_eu_80668974;
    sinkf = *(volatile float*)&lbl_eu_80668978;
    sinkf = *(volatile float*)&lbl_eu_8066897C;
    volatile double sinkd = *(volatile double*)&lbl_eu_80668980;
    sinkf = *(volatile float*)&lbl_eu_80668988;
    sinkf = *(volatile float*)&lbl_eu_8066898C;
    (void)sinkf;
    (void)sinki;
    (void)sinkd;
}
