// Anchor for the TU; the real .sdata2 touch lives at the bottom
// (dummy must see the label declarations first).
extern "C" void dummy();

#include <revolution/GX.h>
#include "monolib/math/CMat34.hpp"

// Color/alpha view of CfGimmickEne for the marker-quad renderer. Kept
// local so this data-only TU does not pull CfGimmickEne.hpp's label
// externs (they conflict with the section-placed definitions below).
struct CfGimmickEneQuad {
    u8 _00[0x97];
    u8 colorR;
    u8 colorG;
    u8 colorB;
    u8 _9A[0xA9 - 0x9A];
    u8 field_A9;
};

// Typified retail data (replaces the old generated byte blobs). Layout from
// build/us/asm/kyoshin/cf/CfGimmickEne.s.

// .rodata 0x58: type string + BDAT column-name blob.
__declspec(section ".rodata") __attribute__((used))
const char lbl_eu_8050E690[0x14] = "cf::CfGimmickEne";
__declspec(section ".rodata") __attribute__((used))
const char lbl_eu_8050E6A4[0x44] =
    "eneID\0artID\0state\0EFF\0SE\0envSE\0wet\0hour\0spWF\0startF\0watiF\0endF";

// .sdata2 0x48: short tags (with retail padding) then float pool.
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668948[8] = "aLOD1";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668950[8] = "aType";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668958[8] = "aSpd";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668960[4] = "aCL";
__declspec(section ".sdata2") __attribute__((used))
const char lbl_eu_80668964[4] = "cl1";
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668968 = 1.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066896C = 0.0f;
__declspec(section ".sdata2") __attribute__((used))
const int lbl_eu_80668970 = -1;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668974 = -1.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668978 = 1.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066897C = 0.01f;
__declspec(section ".sdata2") __attribute__((used))
const double lbl_eu_80668980 = 4503599627370496.0;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_80668988 = 255.0f;
__declspec(section ".sdata2") __attribute__((used))
const float lbl_eu_8066898C = 0.1f;

// .sdata 0x28: RTTI-ish pointer pairs (reloc sites are zero bytes in .o).
extern char lbl_eu_8050DBC4[];
extern char lbl_eu_805379F0[];
extern char lbl_eu_8050DBD8[];
extern char lbl_eu_8050DBF0[];
extern char lbl_eu_8050DC08[];
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_80662990[2] = { lbl_eu_8050DBC4, lbl_eu_805379F0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_80662998[2] = { lbl_eu_8050DBD8, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629A0[2] = { lbl_eu_8050DBF0, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629A8[2] = { lbl_eu_8050DC08, 0 };
__declspec(section ".sdata") __attribute__((used))
const void* lbl_eu_806629B0[2] = { lbl_eu_80668964, 0 };

// .data 0x7C: dtor-descriptor triples, dispatch rows, tag-pointer table.
extern "C" {
void __dt__Q22UI17CPassiveSkillLineFv();
void __dt__Q22UI17CPassiveSkillInfoFv();
void __dt__Q22UI16CPassiveSkillCurFv();
void func_8026EA20();
void func_8026EBA8();
void func_8026EC80();
void func_8026ECEC();
void func_8026F254();
void func_8026F31C();
}
struct EneTagTrio {
    const void* a;
    const void* b;
    const void* c;
};
struct EneDataRow {
    const void* a;
    unsigned int b;
    const void* c;
};
// NOTE: MWCC 8-aligns .data objects whose size is a multiple of 8, so
// retail's packed layout needs every object sized off the 8-grid: single
// 12-byte rows (not one 72-byte table) and a 12+4 split for the tags.
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_805379FC = {
    lbl_eu_80662998, 0, (const void*)__dt__Q22UI17CPassiveSkillLineFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A08 = {
    lbl_eu_806629A0, 0, (const void*)__dt__Q22UI17CPassiveSkillInfoFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A14 = {
    lbl_eu_806629A8, 0, (const void*)__dt__Q22UI16CPassiveSkillCurFv,
};
__declspec(section ".data") __attribute__((used))
const EneDataRow lbl_eu_80537A20 = { 0, 0xFFFFFFFFu, (const void*)func_8026EA20 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow1 = { 0, 0xFFFFFFFFu, (const void*)func_8026EBA8 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow2 = { 0, 0xFFFFFFFFu, (const void*)func_8026EC80 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow3 = { 0, 0xFFFFFFFFu, (const void*)func_8026ECEC };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow4 = { 0, 0xFFFFFFFFu, (const void*)func_8026F254 };
__declspec(section ".data") __attribute__((used))
static const EneDataRow s_dispatchRow5 = { 0, 0xFFFFFFFFu, (const void*)func_8026F31C };
__declspec(section ".data") __attribute__((used))
const EneTagTrio lbl_eu_80537A68 = { lbl_eu_80668948, lbl_eu_80668950, lbl_eu_80668958 };
__declspec(section ".data") __attribute__((used))
static const void* s_tagD = lbl_eu_80668960;

extern "C" __declspec(noinline) void func_8026E7F8(CfGimmickEneQuad* self, int arg) {
    (void)arg;

    GXSetCurrentMtx(0);
    GXLoadPosMtxImm(*ml::CMat34::identity, 0);
    GXSetVtxAttrFmt(GX_VTXFMT0, GX_VA_POS, GX_POS_XYZ, GX_F32, 0);
    GXSetAlphaCompare(GX_GEQUAL, 1, GX_AOP_AND, GX_LEQUAL, 0xff);
    GXSetBlendMode(GX_BM_BLEND, GX_BL_SRCALPHA, GX_BL_INVSRCALPHA, GX_LO_CLEAR);
    GXSetZMode(GX_TRUE, GX_LEQUAL, GX_FALSE);
    GXSetCullMode(GX_CULL_NONE);
    GXSetNumTexGens(0);
    GXSetNumTevStages(1);
    GXSetNumChans(1);
    GXSetChanCtrl(GX_COLOR0A0, GX_ENABLE, GX_SRC_REG, GX_SRC_REG, GX_LIGHT_NULL,
                  GX_DF_NONE, GX_AF_NONE);
    GXSetNumTevStages(1);
    GXSetTevOrder(GX_TEVSTAGE0, GX_TEXCOORD_NULL, GX_TEXMAP_NULL, GX_COLOR0A0);
    GXSetTevAlphaIn(GX_TEVSTAGE0, GX_CA_ZERO, GX_CA_ZERO, GX_CA_ZERO, GX_CA_RASA);
    GXSetTevAlphaOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE,
                    GX_TEVPREV);
    GXSetTevColorIn(GX_TEVSTAGE0, GX_CC_ZERO, GX_CC_ZERO, GX_CC_ZERO, GX_CC_RASC);
    GXSetTevColorOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE,
                    GX_TEVPREV);
    GXClearVtxDesc();
    GXSetVtxDesc(GX_VA_POS, GX_DIRECT);

    GXColor color = *reinterpret_cast<const GXColor*>(&lbl_eu_80668970);
    GXSetChanMatColor(GX_COLOR0A0, color);
    color.r = self->colorR;
    color.g = self->colorG;
    color.b = self->colorB;
    color.a = self->field_A9;
    GXSetChanAmbColor(GX_COLOR0A0, color);

    GXBegin(GX_TRIANGLEFAN, GX_VTXFMT0, 4);
    // Literals keep per-FIFO lfs reloads (100% insn). Named/pointer refs
    // CSE or reschedule. Residual is @N vs lbl_eu_80668974/78 reloc names.
    GXPosition3f32(-1.0f, 1.0f, -1.0f);
    GXPosition3f32(1.0f, 1.0f, -1.0f);
    GXPosition3f32(1.0f, -1.0f, 1.0f);
    GXPosition3f32(-1.0f, -1.0f, -1.0f);
}

extern "C" void dummy() {
    // Anchor the .sdata2 scalar pool above: MWCC drops unreferenced const
    // scalars, so volatile-read each label in retail order (emission =
    // first use). Plain arithmetic folds at compile time and drops the
    // labels, so every read goes through a volatile pointer.
    volatile float sinkf;
    sinkf = *(volatile float*)&lbl_eu_80668968;
    sinkf = *(volatile float*)&lbl_eu_8066896C;
    volatile int sinki = *(volatile int*)&lbl_eu_80668970;
    sinkf = *(volatile float*)&lbl_eu_80668974;
    sinkf = *(volatile float*)&lbl_eu_80668978;
    sinkf = *(volatile float*)&lbl_eu_8066897C;
    volatile double sinkd = *(volatile double*)&lbl_eu_80668980;
    sinkf = *(volatile float*)&lbl_eu_80668988;
    sinkf = *(volatile float*)&lbl_eu_8066898C;
    (void)sinkf;
    (void)sinki;
    (void)sinkd;
}
