// Generated by tools/coop/lbls_gen.py -- do not edit by hand.
// Centralized retail data-label declarations for one area.
//
// Plain `extern` at global scope: MWCC never mangles global-scope data
// names, so the emitted reloc is exactly the retail name (lbl_eu_XXXX),
// identical to `extern "C"` (verified Wii/1.1). `extern "C"` is only
// required inside namespace blocks; declarations here are global-scope.
#pragma once

#include <types.h>

extern f32 lbl_80518684;
extern f32 lbl_80518688;
extern f32 lbl_8051868C;
extern char lbl_80551F90;
extern char lbl_80560608;
extern char lbl_80560650;
extern char lbl_80560660;
extern char lbl_80560678;
extern char lbl_80560690;
extern char lbl_805606C8;
extern char lbl_8056077C;
extern char lbl_805607B4;
extern char lbl_805607C4;
extern char lbl_80560860;
extern char lbl_80560878;
extern char lbl_805608AC;
extern char lbl_80560900;
extern char lbl_80562504;
extern char lbl_80562530;
extern char lbl_80562544;
extern char lbl_805625AC;
extern char lbl_805625D0;
extern char lbl_805625E0;
extern char lbl_805625F0;
extern char lbl_80562604;
extern char lbl_80562618;
extern char lbl_805627BC;
extern char lbl_8056288C;
extern char lbl_805629E8;
extern char lbl_80562A20;
extern char lbl_80562AE0;
extern char lbl_80562AF8;
extern char lbl_80562B4C;
extern char lbl_80562BD8;
extern char lbl_80562BF0;
extern char lbl_80562C2C;
extern char lbl_80562D24;
extern char lbl_805630F4;
extern char lbl_8056311C;
extern char lbl_80665B70;
extern char lbl_80665B78;
extern char lbl_80665D50;
extern char lbl_80665D54;
extern char lbl_80665D5C;
extern u32 lbl_8066C260;
extern u16 lbl_8066C264;
extern u8 lbl_8066C266;
extern char lbl_eu_80549D1C;

