// Generated by tools/coop/lbls_gen.py -- do not edit by hand.
// Centralized retail data-label declarations for one area.
//
// Plain `extern` at global scope: MWCC never mangles global-scope data
// names, so the emitted reloc is exactly the retail name (lbl_eu_XXXX),
// identical to `extern "C"` (verified Wii/1.1). `extern "C"` is only
// required inside namespace blocks; declarations here are global-scope.
#pragma once

#include <types.h>

extern char lbl_eu_8051D520;
extern char lbl_eu_8051D530;
extern char lbl_eu_8051D548;
extern char lbl_eu_8051D560;
extern char lbl_eu_8051D578;
extern char lbl_eu_8051D590;
extern char lbl_eu_8051D5A8;
extern char lbl_eu_8051D5C0;
extern char lbl_eu_8051D5D0;
extern char lbl_eu_8051D5E4;
extern char lbl_eu_8051D5F8;
extern char lbl_eu_8051D620;
extern char lbl_eu_8051D630;
extern char lbl_eu_8051D798;
extern char lbl_eu_8051D7C0;
extern s16 lbl_eu_8051FC40;
extern f32 lbl_eu_8051FD40;
extern void* lbl_eu_8056AFF0;
extern u8 lbl_eu_8056B084;
extern char lbl_eu_8061A750;
extern char lbl_eu_8061B574;
extern u8 lbl_eu_8061DFA0;
extern char lbl_eu_8061FAB8;
extern u32 lbl_eu_8066346C;
extern char lbl_eu_80665458;
extern u32 lbl_eu_806654CC;
extern bool lbl_eu_80665508;
extern int lbl_eu_8066550C;
extern f32 lbl_eu_80669AE0;
extern f32 lbl_eu_80669AE4;
extern f32 lbl_eu_80669B00;
extern f32 lbl_eu_80669B04;
extern f32 lbl_eu_80669B08;
extern f32 lbl_eu_80669BC8;
extern f32 lbl_eu_80669C48;
extern f32 lbl_eu_80669C4C;
extern f32 lbl_eu_80669C50;
extern f32 lbl_eu_80669CA8;
extern f32 lbl_eu_80669DA0;
extern f32 lbl_eu_8066A058;
extern f32 lbl_eu_8066A05C;
extern f32 lbl_eu_8066A100;

