// Generated by tools/coop/lbls_gen.py -- do not edit by hand.
// Centralized retail data-label declarations for one area.
//
// Plain `extern` at global scope: MWCC never mangles global-scope data
// names, so the emitted reloc is exactly the retail name (lbl_eu_XXXX),
// identical to `extern "C"` (verified Wii/1.1).
//
// Dual-mode through the shared LBLS_ENTRY macro (defined in types.h):
// the MWCC matching build sees declarations only (the retail image
// supplies all data); non-MWCC builds (PC port) get definitions -- the
// generated data TU (port/data_defs.cpp) defines LBLS_DEFINE_DATA
// before including types.h so storage exists exactly once; every other
// TU sees `extern`. Initializers carry retail bytes when a DOL is
// present (decoded per type), typed zeros otherwise.
//
// Class/typedef-typed labels include their declaring headers. The
// extern-only section (object-typed labels) is suppressed in the data
// TU: those definitions must stay raw bytes in data_defs.cpp for
// fidelity, and a real-typed extern + raw definition cannot coexist
// in one TU (type mismatch).
#pragma once

#include <types.h>

LBLS_ENTRY(f32 lbl_80518684, f32 lbl_80518684, (-10000.0f))
LBLS_ENTRY(f32 lbl_80518688, f32 lbl_80518688, (-15000.0f))
LBLS_ENTRY(f32 lbl_8051868C, f32 lbl_8051868C, (10.0f))
LBLS_ENTRY(char lbl_80551F90[], char lbl_80551F90[11], ("2004/02/01"))
LBLS_ENTRY(char lbl_80560608[], char lbl_80560608[71], ("<< RVL_SDK - WPAD \trelease build: Jun 22 2009 18:33:21 (0x4302_145) >>"))
LBLS_ENTRY(char lbl_80560650[], char lbl_80560650[14], ("WBCReadDummy\n"))
LBLS_ENTRY(char lbl_80560660[], char lbl_80560660[22], ("WBCSetZEROPointDummy\n"))
LBLS_ENTRY(char lbl_80560678[], char lbl_80560678[22], ("WBCGetTGCWeightDummy\n"))
LBLS_ENTRY(char lbl_80560690[], char lbl_80560690[39], ("Wait for %d ms until start reconnect!\n"))
LBLS_ENTRY(char lbl_805606C8[], char lbl_805606C8[27], ("handle = %d, repid = %02x\n"))
LBLS_ENTRY(char lbl_8056077C[], char lbl_8056077C[55], (" ==>this error means that the firmware is for NDEV %s\n"))
LBLS_ENTRY(char lbl_805607B4[], char lbl_805607B4[13], ("2.1 or later"))
LBLS_ENTRY(char lbl_805607C4[], char lbl_805607C4[156], ("Nintendo RVL-WBC\x00""\x00""\x00""\x00""connection is %s\n\x00""\x00""\x00""Nintendo RVL-CNT\x00""\x00""\x00""\x00""clean up command queue\n\x00""WARNING: disconnection for device handle not assigned to channel.\n\x00""\x00""\x00""\x00""\x00"""))
LBLS_ENTRY(char lbl_80560860[], char lbl_80560860[24], ("HID Parser reports: %d\n"))
LBLS_ENTRY(char lbl_80560878[], char lbl_80560878[51], ("WARNING: Overwritten the callback needed by KPAD.\n"))
LBLS_ENTRY(char lbl_805608AC[], char lbl_805608AC[82], ("         Please call KPADSetSamplingCallback instead of WPADSetSamplingCallback.\n"))
LBLS_ENTRY(char lbl_80560900[], char lbl_80560900[80], ("         Please call KPADSetConnectCallback instead of WPADSetConnectCallback.\n"))
LBLS_ENTRY(char lbl_80562504[], char lbl_80562504[41], ("__wudSyncFlushCallback() : %d, Sync: %d\n"))
LBLS_ENTRY(char lbl_80562530[], char lbl_80562530[17], ("Nintendo RVL-CNT"))
LBLS_ENTRY(char lbl_80562544[], char lbl_80562544[104], ("Nintendo RVL-WBC\x00""\x00""\x00""\x00""Found the registered WBC in database\n\x00""\x00""\x00""Removed WBC data\n\x00""\x00""\x00""new entry index is %d\n\x00"""))
LBLS_ENTRY(char lbl_805625AC[], char lbl_805625AC[31], ("%d devices is stored into SC.\n"))
LBLS_ENTRY(char lbl_805625D0[], char lbl_805625D0[16], ("NANDOpen. [%d]\n"))
LBLS_ENTRY(char lbl_805625E0[], char lbl_805625E0[16], ("NANDSeek. [%d]\n"))
LBLS_ENTRY(char lbl_805625F0[], char lbl_805625F0[17], ("NANDWrite. [%d]\n"))
LBLS_ENTRY(char lbl_80562604[], char lbl_80562604[17], ("NANDClose. [%d]\n"))
LBLS_ENTRY(char lbl_80562618[], char lbl_80562618[420], ("Pairing Done\n\x00""\x00""\x00""write stored link key\n\x00""\x00""addr : %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""key  : %02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x\n\x00""Cancel searching because 4 connections exist.\n\x00""\x00""/title/00010004/52464e4a/data/RPHealth.dat\x00""\x00""WbcSaveData: %s\n\x00""\x00""\x00""\x00""WBC to WiiFit\n\x00""\x00"" %02x %02x %02x %02x %02x %02x\n\x00"" %02x %02x %02x %02x %02x %02x %02x %02x\n\x00""\x00""\x00"" %02x%02x%02x%02x\n\x00""\x00""WARNING: Illigal status\n\x00""\x00""\x00"""))
LBLS_ENTRY(char lbl_805627BC[], char lbl_805627BC[208], ("__wudDeleteFlushCallback() : %d, Delete: %d\n\x00""\x00""\x00""\x00""hci_version   : %02x\n\x00""\x00""\x00""hci_revision  : %04x\n\x00""\x00""\x00""lmp_version   : %02x\n\x00""\x00""\x00""lmp_subversion: %04x\n\x00""\x00""\x00""manufacturer  : %04x\n\x00""\x00""\x00"" ==> 2045 firmware ver.002.003.014.%d\n\x00"""))
LBLS_ENTRY(char lbl_8056288C[], char lbl_8056288C[348], ("__wudInitFlushCallback() : %d, Init: %d\n\x00""\x00""\x00""\x00""name : %s\n\x00""\x00""Nintendo RVL-CNT-01\x00""Error: the workarea for synchronizing WBC pairing information is not allocated.\n\x00""\x00""\x00""\x00""\x00""\x00""\x00""\x00""NANDInit. [%d]\n\x00""CRC  = %d:%08x\n\x00""CRC' = %d:%08x\n\x00""CRC Error on WiiFit SaveData.\n\x00""\x00""WiiFit does not register WBC yet.\n\x00""\x00""LinkKey saved in WiiFit SaveData is invalid.\n\x00""\x00""\x00""WBC from WiiFit\n\x00""\x00""\x00"""))
LBLS_ENTRY(char lbl_805629E8[], char lbl_805629E8[49], ("__wudShutdownFlushCallback() : %d, Shutdown: %d\n"))
LBLS_ENTRY(char lbl_80562A20[], char lbl_80562A20[24], ("__wudClearControlBlock\n"))
LBLS_ENTRY(char lbl_80562AE0[], char lbl_80562AE0[24], ("WUDSetDisableChannel()\n"))
LBLS_ENTRY(char lbl_80562AF8[], char lbl_80562AF8[27], ("BTM_SetAfhChannels() : %d\n"))
LBLS_ENTRY(char lbl_80562B4C[], char lbl_80562B4C[140], ("Initialize the BCM2045 firmware complete.\n\x00""\x00""Reset again!\n\x00""\x00""\x00""Install the patches\n\x00""\x00""\x00""\x00""Download the patch codes [%d]\n\x00""\x00""RemovePatch Callback\n\x00""\x00"""))
LBLS_ENTRY(char lbl_80562BD8[], char lbl_80562BD8[24], ("SuperPeekPoke Callback\n"))
LBLS_ENTRY(char lbl_80562BF0[], char lbl_80562BF0[60], ("RemovePatch\n\x00""\x00""\x00""\x00""__wudAppendRuntimePatch()\n\x00""\x00""SuperPeekPoke\n\x00"""))
LBLS_ENTRY(char lbl_80562C2C[], char lbl_80562C2C[248], ("start __wudInitSub()\n\x00""\x00""\x00""BTA_DmAddDevice(): %d\n\x00""\x00""\x00""\x00""\x00""\x00""BTA_HhAddDev()\n\x00""WUDiRemoveDevice : \n\x00""\x00""\x00""\x00"" handle : %d,  addr : %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""\x00""remove device info from database.\n\x00""\x00""BTA_HhRemoveDev()\n\x00""\x00"" handle : %d\n\x00""\x00""\x00""BTA_DmRemoveDevice(): %d\n\x00""\x00"""))
LBLS_ENTRY(char lbl_80562D24[], char lbl_80562D24[636], ("WARNING: USB_CLOSE_FAILURE!\n\x00""\x00""\x00""\x00""__wudCleanupStackCallback: \x00""BTA_ENABLE_EVT\n\x00""host : %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""BTA_DISABLE_EVT\n\x00""\x00""\x00""\x00""BTA_DM_PIN_REQ_EVT\n\x00""BTA_DM_AUTH_CMPL_EVT\n\x00""\x00""\x00""  addr : %02x:%02x:%02x:%02x:%02x:%02x\n\x00""  key  : %02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""  result = %d\n\x00""\x00""BTA_DM_AUTHORIZE_EVT\n\x00""\x00""\x00""BTA_DM_LINK_UP_EVT\n\x00""   addr : %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""\x00""%s --> %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""not paired\x00""\x00""4 links exist\x00""\x00""\x00""BTA_DM_LINK_DOWN_EVT\n\x00""\x00""\x00""result: %d\n\x00""this device in not paired\n\x00""\x00""WARNING: link num count is reset.\n\x00""\x00""BTA_DM_SIG_STRENGTH_EVT\n\x00""\x00""\x00""\x00""BTA_DM_BUSY_LEVEL_EVT\n\x00"""))
LBLS_ENTRY(char lbl_805630F4[], char lbl_805630F4[37], ("__wudDeviceStatusEventStackCallback\n"))
LBLS_ENTRY(char lbl_8056311C[], char lbl_8056311C[852], ("---- WARNING: USB FATAL ERROR! ----\n\x00""\x00""\x00""\x00""BTM_CB_EVT_RETURN_LINK_KEYS\n\x00""\x00""\x00""\x00""BD_ADDR:  %02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""\x00""LINKKEY: %02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x\n\x00""\x00""\x00""this device is not stored in NAND\n\x00""\x00""   LAST: %02x:%02x:%02x:%02x:%02x:%02x\n\x00""BTM_CB_EVT_READ_STORED_LINK_KEYS\n\x00""\x00""\x00""  status: %d  max_keys: %d  num_keys: %d\n\x00""\x00""\x00""BTM_CB_EVT_WRITE_STORED_LINK_KEYS\n\x00""\x00""  status: %d  num_keys: %d\n\x00""BTM_CB_EVT_DELETE_STORED_LINK_KEYS\n\x00""WARNING: no entry is deleted\n\x00""\x00""\x00""Unknown event\n\x00""\x00""__wudPowerMangeEventStackCallback\n\x00""\x00""hci_status = %d\n\x00""\x00""\x00""\x00""Unknown device is connected and changes the connection type!!!!\n\x00""\x00""\x00""\x00"" addr = %02x:%02x:%02x:%02x:%02x:%02x,  status = %d\n\x00""\x00""\x00""\x00""_WUDEnableTestMode\n\x00""_WUDStartSyncDevice()\n\x00""\x00""_WUDDeleteStoreDevice()\n\x00""\x00""\x00""\x00""dev number = %d\n\x00""\x00""\x00""\x00""Not Found\x00""\x00""\x00""Found the registered WBC\n\x00""\x00""\x00""Removed\n\x00""\x00""\x00""\x00""Not Found WBC\n\x00"""))
LBLS_ENTRY(char lbl_80665B70[], char lbl_80665B70[8], ("%016llx"))
LBLS_ENTRY(char lbl_80665B78[], char lbl_80665B78[3], ("%d"))
LBLS_ENTRY(char lbl_80665D50[], char lbl_80665D50[4], ("2.0"))
LBLS_ENTRY(char lbl_80665D54[], char lbl_80665D54[7], ("opened"))
LBLS_ENTRY(char lbl_80665D5C[], char lbl_80665D5C[7], ("closed"))
LBLS_ENTRY(u32 lbl_8066C260, u32 lbl_8066C260, (0x57696900))
LBLS_ENTRY(u16 lbl_8066C264, u16 lbl_8066C264, (0x0004))
LBLS_ENTRY(u8 lbl_8066C266, u8 lbl_8066C266, (0x48))
LBLS_ENTRY(char lbl_eu_80549D1C[], char lbl_eu_80549D1C[16], ("bar_00\x00""\x00""bar_10\x00"""))

