// Generated by tools/coop/lbls_gen.py -- do not edit by hand.
// Class/typedef-typed retail data labels: real-type externs for every
// build (matching + PC port). Definitions stay raw bytes in
// port/data_defs.cpp; this header is NOT included by data_defs.cpp
// so its type providers cannot clash with the SDK globals it defines.
#pragma once

#include <types.h>
#include <monolib/coli/code_804B2FF0.hpp>
#include <monolib/coli/coli_types.hpp>
#include <monolib/core/code_804DEDA8.hpp>
#include <monolib/device/CDeviceFileDvd.hpp>
#include <monolib/device/CDeviceFontInfoRom.hpp>
#include <monolib/lod/code_804645CC.hpp>
#include <monolib/mpfsys/MPFDrawDisplayList.hpp>
#include <monolib/mpfsys/MPFDrawMdlColor.hpp>
#include <nw4r/g3d/g3d_state.h>
#include <nw4r/g3d/res/g3d_resfile.h>
#include <nw4r/math/math_geometry.h>
#include <nw4r/snd/snd_AxfxImpl.h>
#include <nw4r/ut/ut_RuntimeTypeInfo.h>
#include <revolution/gx/GXFrameBuf.h>
#include <revolution/mem/mem_allocator.h>

extern GXRenderModeObj lbl_eu_8056BE38;
extern LodTexCoordSetup lbl_eu_8056D728[];
extern mpfsys::MPFDrawMdlColor lbl_eu_8056DBC0;
extern FogState lbl_eu_8061AF60;
extern GXRenderModeObj lbl_eu_8061F9D4;
extern mpfsys::MPFDrawDisplayList* lbl_eu_80658488[];
extern FogState lbl_eu_8065FCA0;
extern CScheduleItemPool lbl_eu_80661718;
extern nw4r::math::FRUSTUM* lbl_eu_80665468;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665470;
extern MEMAllocator* lbl_eu_80665478;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665498;
extern nw4r::snd::detail::AxfxImpl* lbl_eu_806654C8;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_806654D0;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_806654F8;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665520;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665538;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665548;
extern nw4r::ut::detail::RuntimeTypeInfo lbl_eu_80665550;
extern CDeviceFileDvd* lbl_eu_80665670;
extern CDeviceFontInfoRom* lbl_eu_80665688;
extern nw4r::g3d::ResFileData* lbl_eu_80665848;
extern ml::coli::CColiObject* lbl_eu_80665910;
extern ml::coli::CColiObject* lbl_eu_80665914;
extern ml::coli::CColiObject* lbl_eu_80665918;
extern ml::coli::CColiObject* lbl_eu_8066591C;
extern ml::coli::CColiObject* lbl_eu_80665920;
extern ml::coli::CColiObject* lbl_eu_80665928;
extern ml::coli::CColiObject* lbl_eu_8066592C;
extern ml::coli::CColiObject* lbl_eu_80665930;
extern CColiBounds* lbl_eu_80665944;
extern CColiQx* lbl_eu_80665948;

