"""Git operations for the harness: branches, worktree commits, and the
concurrent-safe 3-way merge drivers for the shared registries.

The registries (targets.json, attempts.jsonl, symbols.txt) are written by
every batch worktree. A plain `git merge` would conflict on them constantly,
so the harness registers custom merge drivers (local to the main checkout,
via .git/config + .git/info/attributes):

  targets.json    per-target-id 3-way union  (merge_targets.py)
  attempts.jsonl  unique-line union          (merge_attempts.py)
  symbols.txt     per-key 3-way union        (merge_symbols.py)
  README/progress-map.svg  keep ours         (regenerated by pre-commit hook)

Merge drivers receive %O (base) %A (ours/main) %B (theirs/branch) and must
write the merged result to %A, exiting 0.
"""
import os
import shlex
import subprocess

from .common import HARNESS, ROOT, VENV_PY, sh


def _git(args, cwd=None, timeout=300):
    """Run git in the repo root by default (the harness may be invoked anywhere)."""
    return sh(["git"] + args, cwd=cwd or ROOT, timeout=timeout)


def branch_exists(branch):
    r = _git(["branch", "--list", branch])
    return r.returncode == 0 and bool(r.stdout.strip())


def branch_commits_ahead(branch, base="main"):
    r = _git(["rev-list", "--count", f"{base}..{branch}"])
    return int(r.stdout.strip() or "0") if r.returncode == 0 else 0


def delete_branch(branch):
    r = _git(["branch", "-d", branch])
    return r.returncode == 0


def force_delete_branch(branch):
    r = _git(["branch", "-D", branch])
    return r.returncode == 0


def read_file_from_branch(branch, path):
    r = _git(["show", f"{branch}:{path}"])
    return r.stdout if r.returncode == 0 else None


def commit_worktree_changes(worktree_path, message):
    """Commit any uncommitted changes in a batch worktree (best-effort)."""
    r = _git(["status", "--porcelain"], cwd=worktree_path)
    if r.returncode != 0 or not r.stdout.strip():
        return False
    _git(["add", "-A"], cwd=worktree_path)
    r = _git(["commit", "-m", message], cwd=worktree_path)
    return r.returncode == 0


# --- merge driver registration ---------------------------------------------

MERGE_DRIVERS = {
    "paseo-targets": {
        "script": "merge_targets.py",
        "patterns": ["tools/coop/targets.json"],
    },
    "paseo-attempts": {
        "script": "merge_attempts.py",
        "patterns": ["docs/evidence/decomp/attempts.jsonl"],
    },
    "paseo-symbols": {
        "script": "merge_symbols.py",
        "patterns": ["config/*/symbols.txt"],
    },
    "paseo-keep-ours": {
        "script": None,
        "patterns": ["README.md", "assets/progress-map.svg"],
    },
}

ATTRS_PATH = ROOT / ".git" / "info" / "attributes"


def ensure_merge_drivers():
    """Register merge drivers in the local (main checkout) git config."""
    changed = False
    for name, cfg in MERGE_DRIVERS.items():
        if cfg["script"]:
            script = HARNESS / cfg["script"]
            driver = f"{shlex.quote(str(VENV_PY))} {shlex.quote(str(script))} %O %A %B"
        else:
            driver = "true"  # keep ours
        cur = _git(["config", "--local", "--get", f"merge.{name}.driver"])
        if cur.returncode != 0 or cur.stdout.strip() != driver:
            _git(["config", "--local", f"merge.{name}.driver", driver])
            changed = True

    if ATTRS_PATH.exists():
        existing = ATTRS_PATH.read_text()
    else:
        existing = ""
    lines = existing.rstrip("\n").split("\n") if existing.strip() else []
    have = set(l for l in lines if l.strip())
    added = []
    for name, cfg in MERGE_DRIVERS.items():
        for pat in cfg["patterns"]:
            line = f"{pat} merge={name}"
            if line not in have:
                added.append(line)
    if added:
        with open(ATTRS_PATH, "a") as f:
            if lines:
                f.write("\n")
            f.write("\n".join(added) + "\n")
        changed = True
    return changed


# --- merge-back ------------------------------------------------------------

# Shared registries written by every agent in the main tree (and by other
# sections' agents running there). Before a merge, checkpoint-commit them so
# git doesn't refuse the merge over other agents' dirty registry writes.
REGISTRY_FILES = [
    "tools/coop/targets.json",
    "tools/coop/targets.certs.jsonl.gz",
    "docs/evidence/decomp/attempts.jsonl",
    "config/us/symbols.txt",
    "README.md",
    "assets/progress-map.svg",
]


def checkpoint_registry():
    """Commit dirty shared-registry files in the main checkout (if any)."""
    r = _git(["status", "--porcelain", "--", *REGISTRY_FILES])
    if r.returncode != 0 or not r.stdout.strip():
        return False
    _git(["add", "--", *REGISTRY_FILES])
    r = _git(["commit", "-m", "paseo-harness: checkpoint shared registry before merge"])
    return r.returncode == 0


def merge_batch(branch, message, base="main"):
    """Merge a batch branch into the current checkout (main).

    Returns (status, detail):
      ("merged",  "")            merged cleanly; branch deleted
      ("conflict", stderr)       merge conflicts; aborted, branch kept
      ("deferred", stderr)       merge refused (dirty sources etc.); branch kept
    """
    ensure_merge_drivers()
    checkpoint_registry()
    r = _git(["merge", "--no-ff", "-m", message, branch])
    if r.returncode == 0:
        delete_branch(branch)
        return ("merged", "")

    # a refused merge can leave MERGE_HEAD behind on conflict
    mh = _git(["rev-parse", "-q", "--verify", "MERGE_HEAD"])
    if mh.returncode == 0:
        _git(["merge", "--abort"])
        return ("conflict", (r.stderr or r.stdout)[-2000:])
    return ("deferred", (r.stderr or r.stdout)[-2000:])
